implement adyen payment reporting
openedx-unsupported/edx-analytics-pipeline pull request #281
Opened 2016-08-19 10:52 UTC by zubair-arbi

SOL-1880

### WIP

* Implement `Adyen` daily payment reporting
* Add tests config

**Remaining:**
* Add tests for `Adyen` reporting

@hasnain-naveed @ibrahimahmed443 @douglashall

2016-08-31 11:24 UTC, zubair-arbi commented
@douglashall @HassanJaveed84 please give initial review for this PR.

2016-08-31 12:48 UTC, zubair-arbi commented
@brianhw @mulby please take a look at this PR and guide me how to write tests for it.
Since `adyen` provides `tsv` files so we are using `tsv` directly instead of fetching `csv` files firstand then converting them to `tsv` and example `tsv` file is attached on the related JIRA ticket [SOL-1880](https://openedx.atlassian.net/browse/SOL-1880).

2016-08-31 13:01 UTC, HassanJaveed84 commented on edx/analytics/tasks/reports/adyen.py
> +class IntervalPullFromAdyenTask(DailyPullFromAdyenTask, WarehouseMixin, luigi.WrapperTask):
Should this be PullFromAdyenTaskMixin instead of DailyPullFromAdyenTask ?

2016-08-31 13:03 UTC, HassanJaveed84 commented on edx/analytics/tasks/reports/adyen.py
> +            'output_root': self.warehouse_path,
I think you can just pass in self.output_root 
```'output_root': self.output_root,```
here as it would default to the warehouse_path if None.

2016-08-31 13:08 UTC, mulby commented
@zubair-arbi - First, thanks for building this! We are definitely on the right track here. Here's my initial round of feedback:

1. You can see examples of similar tests for the paypal report pull here: https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/reports/tests/test_paypal.py#L534
2. You will also need to update our acceptance tests to include some fake data here: https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/tests/acceptance/test_financial_reports.py#L30
3. As you develop this, please be *very* careful not to accidentally upload the password for this account. I recommend copying the devstack.cfg file somewhere outside of the repo say "cp config/devstack.cfg /var/tmp/adyen.cfg", modifying it to include the real password and then running with `LUIGI_CONFIG_PATH=/var/tmp/adyen.cfg launch-task ...`
4. Can you point me to a spec for the format of the TSV that we download from adyen? If it contains certain classes of protected information about the user then we will not want to persist the file to S3, and instead just extract the information we need and save that result. We need the final output to look like this:  https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/reports/cybersource.py#L150.

2016-08-31 13:17 UTC, zubair-arbi commented
4) @mulby I have attached a `tsv` file `received_payments_report_2016_08_17.tsv` is on the related [JIRA ticket SOL-1880](https://openedx.atlassian.net/browse/SOL-1880). You can download it and check the fields.

2016-08-31 13:25 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +class IntervalPullFromAdyenTask(DailyPullFromAdyenTask, WarehouseMixin, luigi.WrapperTask):
Yes. Let me change it.

2016-09-01 13:02 UTC, mulby commented
@zubair-arbi awesome, thanks for the sample. I've responded on the JIRA ticket.

2016-09-07 09:30 UTC, zubair-arbi commented
@mulby @brianhw I have updated this PR to read/use selected fields from actual `adyen` payments report by using the column names. Please review.

2016-09-08 12:57 UTC, zubair-arbi commented
@mulby @brianhw @douglashall I have updated this PR by adding a separate task for processing the daily pulled adyen reports and verified that the new task `DailyProcessFromAdyenTask` works locally. Please review.

2016-09-13 20:59 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +        self.url = config.get(section_name, 'url')
I recognize that interval_start is needed in a different class than username, password, and url, but I would move all four out of this mixin and into their respective classes.   I think this mixin should just define the common luigi parameters that need to be passed through.

2016-09-13 21:00 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +    https://docs.adyen.com/developers/reporting-manual#reportdownload
Is there a more specific link that points directly to the payment accounting report?

2016-09-13 21:01 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +    """ A task that reads out adyen reports "Payment Accounting Report" from a
nit: capitalize Adyen

2016-09-13 21:02 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +    Pulls are made for only a single day. It allows runs to performed
nit:  "to performed" => "to be performed".

2016-09-13 21:03 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +        print "auth =======> ", auth
I assume in production we will want the print statements to be removed.

2016-09-13 21:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +                    # Read only settled (sale) or refunded (refund) transaction records
nit: add trailing period.

2016-09-13 21:07 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +            self.interval = date_interval.Custom(self.interval_start, self.interval_end)
Since interval_start is only needed here, I think this is where it should be read from configuration.

2016-09-19 08:01 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +    https://docs.adyen.com/developers/reporting-manual#reportdownload
@brianhw since this class `DailyPullFromAdyenTask` is related to just fetching the subscribed reports so this [report download manual url](https://docs.adyen.com/developers/reporting-manual#reportdownload) from the `reporting-manual` makes more sense here which describes how you can subscribe and automate the report downloading.

For the report structure of `Payment Accounting Report` I have added the [paymentaccountingreportstructure url](https://docs.adyen.com/developers/reporting-manual#paymentaccountingreportstructure) in the method `run` of class `DailyProcessFromAdyenTask` where we process the downloaded report.

2016-09-19 08:03 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        print "auth =======> ", auth
This is just for local testing purpose and will be removed with our finalized commit.

2016-09-19 08:18 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +            self.interval = date_interval.Custom(self.interval_start, self.interval_end)
Done.

2016-09-19 18:47 UTC, mulby commented on requirements/pre.txt
> +pip==8.1.2             # MIT
This change seems unrelated to this PR and kind of risky. Is it needed?

2016-09-19 18:47 UTC, mulby commented on edx/analytics/tasks/reports/adyen.py
> +        self.config_section_name = 'adyen'
In the cybersource task we made this dynamic because we needed to support different credentials for different accounts, so we needed to have multiple sets of credentials stored in the config file. So it uses section names like "cybersource:account_name".

It looks like, in this case, we don't need account-specific credentials so you could probably just use the standard "default_from_config" kwarg when defining the relevant parameters.

2016-09-19 18:47 UTC, mulby commented on edx/analytics/tasks/reports/adyen.py
> +        default=date.today(),
This should be UTC today: `datetime.utcnow().date()`

2016-09-19 18:47 UTC, mulby commented on edx/analytics/tasks/reports/adyen.py
> +        self.username = self.config.get(self.config_section_name, 'username')
As noted above, these can be made normal parameters unless they are sensitive (like the password). The parameters are printed to the log, so I think it makes sense to read the password directly from the config file, but the others could just be normal parameters.

2016-09-19 18:47 UTC, mulby commented on edx/analytics/tasks/reports/adyen.py
> +    def requires(self):
You should be able to omit this.

2016-09-19 18:47 UTC, mulby commented on edx/analytics/tasks/reports/adyen.py
> +        response = requests.get(self.report_url, auth=auth)
We should probably wrap this in some retry logic. I recently added a retry decorator that support exponential backoff:

https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/util/retry.py

You can see a usage here:

https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/util/edx_api_client.py#L88

Not sure what responses they can give us that are "fatal" vs. "retryable", but we should distinguish between them so that the job doesn't fail if the service is temporarily unavailable.

2016-09-19 18:47 UTC, mulby commented on edx/analytics/tasks/reports/adyen.py
> +                        booking_date.date().isoformat(),
We should convert this to UTC before outputting it.

2016-09-19 18:47 UTC, mulby commented on edx/analytics/tasks/reports/adyen.py
> +        url = '{base_url}/MerchantAccount/{merchant_account}/{report_name}_{report_date}.{report_format}'.format(
I'm hoping/assuming that this report_date is UTC?

2016-09-21 11:56 UTC, zubair-arbi commented on requirements/pre.txt
> +pip==8.1.2             # MIT
Previously I was getting issues in installing packages `cffi` and `cryptography` with errors like:
```
build/temp.macosx-10.11-intel-2.7/_openssl.c:433:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^
1 error generated.
error: command 'cc' failed with exit status 1
``` 
and
```
File "/Users/zubairafzal/Workspace/analytics-edx/edx-analytics-pipeline/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 76, in wrapper
    ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
```
So I updated `pip` too while updating some other packages. 

This update is not trivial but I was really surprised to see that we are using such and old version `1.5.6` while the latest version is `8.1.2` with lots of changes and improvements. My suggestion would be to update our packages on consistent basis. On my local machine I had no issues using this version but I you think that is not necessary or we can have a separate PR then I can do as you suggest.

2016-09-21 11:56 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +                        booking_date.date().isoformat(),
Updated

2016-09-21 11:57 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        url = '{base_url}/MerchantAccount/{merchant_account}/{report_name}_{report_date}.{report_format}'.format(
According to your suggestion I have update the PR to use UTC everywhere.

2016-09-21 11:58 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        response = requests.get(self.report_url, auth=auth)
I have added retry logic, please review.

2016-09-21 11:58 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +    def requires(self):
Done

2016-09-21 11:58 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        self.username = self.config.get(self.config_section_name, 'username')
Updated

2016-09-21 11:58 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        default=date.today(),
Done

2016-09-21 12:03 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        self.config_section_name = 'adyen'
I have now moved this as a file level setting `ADYEN_CONFIG_SECTION`.

2016-09-23 03:05 UTC, brianhw reviewed
Looking good.  A few nits, and reverting the requirements.

2016-09-23 03:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +        description='Username for the Adyen account, for which data is being gathered for.',
nit:  either "for which" or "gathered for", but not "for" in both places.

2016-09-23 03:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +
nit: remove blank line.

2016-09-23 03:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +
nit: check PEP8.  It should complain there is an extra line here.

2016-09-23 03:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +        """Generate the url to download a report from a Adyen account.
nit: " from an Adyen account" instead of "from a ..."

2016-09-23 03:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +            report_date=self.run_date.strftime('%Y_%m_%d'),
nit:  we tend to use isoformat() for dates, which use dashes instead of underlines.

2016-09-23 03:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +                    if transaction_type not in ['Refunded', 'Settled']:
Looks like these should really be the keys of TRANSACTION_TYPE_MAP, rather than redefined here.

2016-09-23 03:05 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +}
It would be good to add a comment here that these are the transaction states that we consider relevant.  (And maybe list the other states that are not considered relevant.)

2016-09-23 03:05 UTC, brianhw commented on requirements/pre.txt
> +pip==8.1.2             # MIT
It won't work on our system.  I tried it in a different branch, and the pip upgrade left the system in an inconsistent state that required deleting the virtualenv and starting over.  

I share your pain regarding the Cryptography upgrade.  That currently breaks for me as well, unless it's upgraded to at least 1.0.  But I think all that should be handled in a separate pull request, since it's not at all related to this PR.

2016-09-23 03:05 UTC, brianhw commented on requirements/pre.txt
> +pip==8.1.2             # MIT
I'm betting it's _still_ related to https://openedx.atlassian.net/browse/AN-4322, as that comment suggests.  So it's really related to the version of virtualenv that we use on our Jenkins.

2016-09-26 09:12 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +}
added comment

2016-09-26 09:12 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        description='Username for the Adyen account, for which data is being gathered for.',
done

2016-09-26 09:12 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +
removed extra line

2016-09-26 09:12 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        """Generate the url to download a report from a Adyen account.
changed

2016-09-26 09:14 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +            report_date=self.run_date.strftime('%Y_%m_%d'),
Since this is the making of external `adyen` report url which needs a specific format of date so cannot modify it.

2016-09-26 09:14 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +                    if transaction_type not in ['Refunded', 'Settled']:
good catch. changed

2016-09-27 13:15 UTC, zubair-arbi commented
@brianhw @mulby @douglashall I have addressed your feedback and also added tests for different scenarios. Please review.

2016-09-27 19:42 UTC, brianhw reviewed
Only nits on the code, but a few more comments on the unit tests.

2016-09-27 19:42 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +from edx.analytics.tasks.url import url_path_join
nit: you can put these on the same line.

2016-09-27 19:42 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +        print "auth =======> ", auth
Don't forget! : )

2016-09-27 19:42 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +        response = self.fetch_report(timeout_seconds=self.REPORT_FETCH_TIMEOUT_SECONDS)
nit: not clear on the value of overriding the default value for timeout_seconds here, only to set it to the same value.

2016-09-27 19:42 UTC, brianhw commented on edx/analytics/tasks/reports/adyen.py
> +            report_date=self.run_date.strftime('%Y_%m_%d'),
Yes, my mistake.  It's not our output.

2016-09-27 19:42 UTC, brianhw commented on requirements/test.txt
> +responses==0.5.1
This has a number of dependencies, and it would be good to freeze them as well.   These include requests, and cookies.  The version for requests should be the same as in default.txt, otherwise a newer version may be installed.  It appears this also wasn't done for six, Jinja2, and python-dateutil -- not related to your change, but if you could also freeze those to their default.txt values, that would be great.

2016-09-27 19:42 UTC, brianhw commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +    @responses.activate
I'm not really familiar with either, but is there a particular advantage to using responses rather than httpretty as was used in test_paypal.py?  It seems a little odd to use two different packages if they both accomplish roughly the same kind of testing of payment provider APIs.

2016-09-27 19:42 UTC, brianhw commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +        self.dummy_adyen_report = open(dummy_adyen_report_path, 'r').read()
This is the first case of having an external data fixture in our unit tests.   Looking in our other tests here in reports, all the others inline the data as a multiline string.

2016-09-27 19:42 UTC, brianhw commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +        requests.codes.gateway_timeout          # HTTP Status Code 504
nit:  I've no idea if this would work, but can you use *DEFAULT_RETRY_STATUS_CODES here?  Just curious....

2016-09-28 09:41 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +from edx.analytics.tasks.url import url_path_join
updated

2016-09-28 09:45 UTC, zubair-arbi commented on edx/analytics/tasks/reports/adyen.py
> +        response = self.fetch_report(timeout_seconds=self.REPORT_FETCH_TIMEOUT_SECONDS)
I have update the method `fetch_report` to take a required argument (previously optional) `timeout_seconds` to clear the confusion. This will help us in testing the task `DailyPullFromAdyenTask` with custom `timeout_seconds`.

2016-09-28 09:48 UTC, zubair-arbi commented on requirements/test.txt
> +responses==0.5.1
I have pinned tests dependencies `cookies==2.2.1`, `Jinja2==2.7.3`, `python-dateutil==2.2`, `requests==2.7.0` and `six==1.6.1` w.r.t to our default requirements.

2016-09-28 09:53 UTC, zubair-arbi commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +    @responses.activate
I have to use `responses` in order to mock the secure http request (fetching `adyen` reports) since `httpretty` was unable to mock those calls and I couldn't find a way to achieve this other than monkey patching the `httpretty`. I know this seems redundant to use two different libraries for same purpose but I wanted to write tests close to our prod settings. Suggestions are welcome.

2016-09-28 09:59 UTC, zubair-arbi commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +        self.dummy_adyen_report = open(dummy_adyen_report_path, 'r').read()
I added external data fixture to increase readability (since adding multiple records with different record types can take significant space and also considering individual records to be too long) and improve the unit tests updates in future easily by separating our externally dependent data from our internally processed content.

2016-09-28 10:01 UTC, zubair-arbi commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +        requests.codes.gateway_timeout          # HTTP Status Code 504
Yes, this works 👍

2016-09-28 19:40 UTC, mulby commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +    @responses.activate
We just test with "http://" urls elsewhere in the code. Could you do that here to avoid pulling in the new dependency?

2016-10-05 00:54 UTC, brianhw commented
LGTM.  👍 after squashing.

2016-10-05 13:48 UTC, mulby requested changes
I'd like to remove the `sleep` calls in the unit tests before merging this in.

2016-10-05 13:48 UTC, mulby commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +    @patch('edx.analytics.tasks.reports.adyen.DailyPullFromAdyenTask.REPORT_FETCH_TIMEOUT_SECONDS', 0.5)
We try *very* hard to keep our unit tests running very quickly, we currently are able to run ~1700 tests in 9 seconds. I would strongly prefer we don't introduce a 500 ms delay into one of our tests.

I would either not test this logic, or do something like I did here: https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/util/tests/test_edx_api_client.py#L99

Note that it patches `time.sleep()` and `datetime.utcnow()`

2016-10-07 11:57 UTC, zubair-arbi commented on edx/analytics/tasks/reports/tests/test_adyen.py
> +    @patch('edx.analytics.tasks.reports.adyen.DailyPullFromAdyenTask.REPORT_FETCH_TIMEOUT_SECONDS', 0.5)
@mulby with your suggestion we would have to use timeout of value atleast `0.03` seconds so that there are http calls for adyen reports greater than 1. So now I have removed that test check and replaced timeout with `0.001` seconds which should be fine with our test time target.

2016-10-07 12:11 UTC, zubair-arbi commented
@mulby @brianhw @douglashall @HassanJaveed84  I have squashed and rebased my PR with master and it's ready for final review. There are some unit tests failing related to `CourseEnrollmentTask` with error `UnknownParameterException` for `output_root` which seems unrelated to my changes.

I have couple of questions too:

1. 
how we add prod config settings for `adyen`?
2. 
would merging this PR now would have any negative affect? since we haven't integrated `Adyen` in out system.

2016-10-14 14:41 UTC, zubair-arbi commented
@brianhw @mulby The PR is ready for final review. Both unit tests and acceptance tests are passing now.

2016-10-20 16:24 UTC, brianhw commented
Prod config settings are stored in a separate private repo that we use for storing secure information.  We would need to add Adyen sections to this, to at least define 'merchant_accounts_list' as an empty list.  When we wanted to actually start pulling information from Adyen, we would add entries to 'merchant_accounts_list' and 'company_account'.

Those changes should probably be done in a branch of the secure repo, and then we would run payment-pulling (or all finance) with a different warehouse_path to keep the results separate from production.

2016-10-28 11:31 UTC, mulby approved these changes

2016-10-28 11:32 UTC, mulby commented
@zubair-arbi - this looks good now, but we need to update our production configuration before merging this to master so that it doesn't break production.

Can you create an analytics ticket that specifies the procedure we can use to obtain the proper reporting credentials for Adyen? We can then follow that procedure, update our production config and merge this to master.

2016-10-28 14:51 UTC, zubair-arbi commented
@mulby thanks for follow up. I have created an [analytics ticket AN-8051](https://openedx.atlassian.net/browse/AN-8051) for providing procedure to get production configuration settings. The steps aren't defined yet, I have asked @douglashall for help on describing this procedure.

2017-01-18 16:56 UTC, mulby commented
After some discussion on AN-8051, we've decided to close this until the project is re-prioritized.

2017-01-18 16:56 UTC, closed without merging