Include the ccx_keys package when launching tasks
openedx-unsupported/edx-analytics-pipeline pull request #290
Opened 2016-09-12 15:02 UTC by bdero

Closes https://openedx.atlassian.net/browse/AN-5666.

### Testing instructions:

1. Setup an analytics devstack: https://github.com/edx/edx-documentation/blob/813c5cd23034ac0fc171f7f9b6ab70051b0b5eac/en_us/install_operations/source/installation/analytics/install_analytics.rst#installing-analytics-devstack
1. Checkout this branch: `git checkout bdero/ccx-keys`
1. Create a CCX and add enroll a user in it from within edX: http://edx.readthedocs.io/projects/open-edx-ca/en/latest/set_up_course/custom_courses.html
1. Run the CourseEnrollmentTask:

   ```bash
remote-task --host localhost --user hadoop --remote-name analyticstack --skip-setup --wait CourseEnrollmentTask --interval 2016 --local-scheduler --output-root hdfs://localhost:9000/output/`
```
1. Check the course_enrollment_daily report table to observe that enrollment information for the CCX is in the table (the password for user `read_only` is `password`): 

   ```bash
echo "select id, course_id, created from course_enrollment_daily group by course_id;" | mysql -u read_only -p`
```

2016-09-12 15:03 UTC, edx-webhook commented
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-analytics-pipeline&number=290

2016-09-12 17:12 UTC, pomegranited commented
:+1:  It does what it says on the box! :smile:

Please make the 2 minor changes listed to the task description before creating the OSPR.

- [x] I tested this using the above instructions, with small modifications:
    * Step 4: use `ImportEnrollmentsIntoMysql` task:

       ```
remote-task --host localhost --user hadoop --remote-name analyticstack --skip-setup --wait ImportEnrollmentsIntoMysql --interval 2016 --local-scheduler
```
    * Step 5: Need to provide the database name:

       ```
echo "select id, course_id, created from course_enrollment_daily group by course_id;" | mysql -u read_only -p reports
````
- [x] I read through the code
- [x] Includes documentation - in comments.

2016-09-13 14:53 UTC, bdero commented
Thanks @pomegranited , I updated the PR Description. This is ready for upstream review.

2016-09-14 12:15 UTC, mulby commented
Can we make this configurable?

Other than that it LGTM.

2016-09-14 15:06 UTC, bdero commented
@mulby Sure, would pulling in an config entry from the `event-logs` key be sufficient?

I.e.
```ini
[event-logs]
pattern = .*tracking.log.*
expand_interval = 2 days
source = hdfs://localhost:9000/data/
process_ccx_logs = true
```

2016-09-14 20:48 UTC, mulby commented
I think it warrants a separate section since it's not really event-log specific:

```
[ccx]
enabled = true
```

2016-09-14 22:47 UTC, bdero commented
@mulby Alright, I used that as the config value and rebased. This is ready for further review!

2016-09-15 13:46 UTC, mulby commented on edx/analytics/tasks/launchers/local.py
> +    if configuration.getboolean('ccx', 'enabled', default=True):
Can we make this default to `False`? I suspect most installations won't use this feature.

2016-09-15 13:47 UTC, mulby requested changes

2016-09-16 19:38 UTC, bdero commented on edx/analytics/tasks/launchers/local.py
> +    if configuration.getboolean('ccx', 'enabled', default=True):
Done.

2016-09-19 11:23 UTC, mulby approved these changes

2016-09-19 15:25 UTC, bdero commented
Thanks for approving @mulby - I don't have permission to merge this PR, however. Otherwise I would. :)

2016-09-19 15:27 UTC, pomegranited commented
Hey @bdero  - do you want to squash your commits?  I can merge when you're ready.

2016-09-19 15:31 UTC, bdero commented
@pomegranited Alrighty, all squashed. Thanks.

2016-09-19 15:34 UTC, merged