Fix to acceptance test on analyticstack.
openedx-unsupported/edx-analytics-pipeline pull request #348
Opened 2017-01-10 22:31 UTC by brianhw

For problem response acceptance test, update the pattern used for finding output files.

2017-01-13 04:43 UTC, brianhw commented
Acceptance tests passed.  Awaiting thumbs.

2017-01-13 20:21 UTC, tobz requested changes

2017-01-13 20:21 UTC, tobz commented on edx/analytics/tasks/tests/acceptance/test_problem_response.py
>              actual_output = actual_output_targets[0].open('r').read()
Can you add an assertion before this line that the size of `actual_output_targets` is 1?

2017-01-13 20:21 UTC, tobz commented on edx/analytics/tasks/tests/acceptance/test_problem_response.py
> +            self.assertEqual(len(actual_output_targets), 1, '{} not created in {}'.format(report_file_name, self.report_output_root))
Yay for more detailed logging!

2017-01-13 20:21 UTC, tobz commented on edx/analytics/tasks/tests/acceptance/test_problem_response.py
> +            actual_output_targets = self.get_targets_from_remote_path(self.report_output_root, "*{}".format(report_file_name))
Why do we now want to match anything at the front of the filename?

2017-01-13 20:35 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_problem_response.py
> +            actual_output_targets = self.get_targets_from_remote_path(self.report_output_root, "*{}".format(report_file_name))
Because it's actually comparing against the pattern against the entire path for HDFS paths, whereas for S3 paths it only matches against the part that is below the output_root.   And it turns out that the latter is the filename.  As a result, this only worked on Jenkins but not analyticstack.

2017-01-13 20:37 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_problem_response.py
>              actual_output = actual_output_targets[0].open('r').read()
I'm confused.  That is what the previous line I added was doing, no?

2017-01-13 21:39 UTC, tobz commented on edx/analytics/tasks/tests/acceptance/test_problem_response.py
>              actual_output = actual_output_targets[0].open('r').read()
Ha.  Sorry.  You're right. :)

2017-01-13 21:40 UTC, tobz approved these changes
Alright.  This all looks good to me after your responses.

2017-01-18 14:09 UTC, mulby approved these changes

2017-01-18 16:03 UTC, merged