Document tasks to run to update insights
openedx-unsupported/edx-analytics-pipeline pull request #382
Opened 2017-04-21 18:15 UTC by mulby

As part of our efforts to centralize our documentation, this is a port of this wiki page: https://github.com/edx/edx-analytics-pipeline/wiki/Tasks-to-Run-to-Update-Insights

FYI - @iloveagent57 @azafty468 @tobz @HassanJaveed84

2017-04-28 19:36 UTC, tobz requested changes

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +#. Tweak ``NUM_REDUCE_TASKS`` based on the size of your cluster. If the cluster is not being used for anything else a good rule of thumb is to make ``NUM_REDUCE_TASKS`` equal the number of available
This strikes me as a black magic-y sort of explanation, and even I'm not entirely familiar with what "reduce slots" are or how to definitively determine how many I have.

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +* You can find the source for building edx-analytics-hadoop-util.jar at `https://github.com/edx/edx-analytics-hadoop-util <https://github.com/edx/edx-analytics-hadoop-util>`_.
Why is this JAR file relevant to this workflow?

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +#. There are a bunch of ``s3://`` paths listed below, but those could easily be replaced with ``hdfs://`` paths.
Can you reword this?  Something like...

"Luigi, the underlying scheduler framework, has support for both S3 and HDFS when specifying input and output paths.  All examples where `s3://` is mentioned can be replaced with equivalent `hdfs://` versions."

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +#. "credentials" files are json files should be stored somewhere secure and have the following format
Worth mentioning here that these can (and should?) be in S3 or HDFS via Luigi's built-in `s3://` or `hdfs://` support.

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +The contents of a credentials file look something like this:
This is sort of a duplicate of the aforementioned note in the General Notes section.

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +    ImportEnrollmentsIntoMysql --local-scheduler \
Give an example of what `$FROM_DATE` and `$TO_DATE` should look like?

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +Incremental implementation
Can we rewrite this section to:
- give a simpler explanation of incremental processing
- avoid the minutiae of implementation history

2017-04-28 19:36 UTC, tobz commented on docs/source/running_tasks.rst
> +To load the historical enrollment events, you would need to first run:
Copypasta mishap: "enrollment"

2017-05-01 17:44 UTC, pomegranited commented
@mulby Sorry for my delayed reply! I'll submit a review this week.

2017-05-04 04:27 UTC, brianhw approved these changes
As good, or better, than the original.  Probably better to get it done and revise it later than to pick it apart for too long.   👍

2017-05-04 04:27 UTC, brianhw commented on docs/source/index.rst
> +The following documentation is generated dynamically from comments in the code. There is detailed documentation for every Luigi task.
nit: I don't know if it matters, but I believe that such documentation will be wrapped on display, and that we generally aim to have the source lines be less than 80 characters long.

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +#. I've started to put comments next to some parameters, please feel free to add in your own comments as well. Note that bash will get unhappy if you try to run these commands with those comments in
The first-person comment here sounds weird.   And now that this is no longer a wiki, we're not exactly expecting others to add their own comments anymore.

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +* You can find the source for building edx-analytics-hadoop-util.jar at `https://github.com/edx/edx-analytics-hadoop-util <https://github.com/edx/edx-analytics-hadoop-util>`_.
This jar is needed for any workflow that reads event logs using a manifest file.  Which is pretty much every workflow that is used for insights.  So perhaps this should go in a more general setup section.

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +* You can find the source for building edx-analytics-hadoop-util.jar at `https://github.com/edx/edx-analytics-hadoop-util <https://github.com/edx/edx-analytics-hadoop-util>`_.
Ah, but it's explicitly mentioned here because it's an explicit argument to the answer distribution workflow.  Our first insights-related workflow.

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +      --credentials s3://secure/path/to/result_store_credentials.json [See discussion of credential files above, these should be the credentials for the result store database to write the result to]
nit: end with a period.  And period after "above" and before "These".

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +The contents of a credentials file look something like this:
Maybe make it a separate sub-section up there, and just link to it here.

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +* This uses more up-to-date patterns.
... compared to answer distribution.    (Certainly not our most up-to-date.)

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +* It *does not* require the "enrollment-reports" section. That section is used to generate static CSV reports.
(and is deprecated!)

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +Incremental implementation
In order for documentation to work for people who are using different versions of the code.  This was definitely the case when the section was written.   Perhaps now we would expect that people are on the same version, but were we to add incremental processing to something else, we should indicate what it relates to.   Dating them is one way to deal with that.    Maybe when they get old enough, they can be modified to release names (e.g. ficus), and then when old enough, they can just be left alone.

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +* This no longer supports a separate ``user-country-output`` parameter for intermediate data.  This is now written to a dated partition under ``(warehouse_path)/last_country_of_user/``.
Yeah, so maybe this should also be pulled.   Or say between eucalyptus and ficus.

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +* Still a work in progress - erroneous events can make videos appear to be much longer than they actually are.
I find this to be rather cryptic....    what work is in progress?  what kinds of errors?     But it reminds me of the line about the side view mirror....

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +The workflow assumes that new Hive-ready data has been written persistently to the ``module_engagement`` directory under warehouse_path by ModuleEngagementIntervalTask.  The workflow uses the ``overw
At the moment, the code requires that overwrite_n_days be defined in [enrollments] as well, though the value is actually ignored.   (Part of the external dependency on enrollment data, as mentioned below.]

2017-05-04 04:27 UTC, brianhw commented on docs/source/running_tasks.rst
> +We run the module engagement job nightly, which adds the most recent day to this while it is overwriting the last N days (as set by the ``--overwrite-n-days`` parameter).  This calculates aggregates
I don't know where (or whether) we want to mention this, but open source users are currently trying out two approaches to dealing with an HDFS limitation.  On HDFS, it is not possible to move files to new names that already exist.  The history jobs do this.  To get around this, folks either avoid running history or they avoid ovewriting it.  That means they either manually delete previous data, and set --overwrite-n-days to a large value to regenerate it all from scratch, or they run the regular job with --overwrite-n-days set to zero.

2017-05-05 06:44 UTC, pomegranited approved these changes
:+1: Major step forwards to making this information consolidated and visible  Thank you!

I've left some comments, but none are showstoppers.

- [x] I tested this by running `make docs` and viewing the generated files in my browser.
- [x] I read through the code
- [x] I checked for accessibility issues - Voiceover can read them :)
- [x] Includes documentation - heaps!

2017-05-05 06:44 UTC, pomegranited commented on docs/source/running_tasks.rst
> +#. There are a bunch of ``s3://`` paths listed below, but those could easily be replaced with ``hdfs://`` paths.
+1

2017-05-05 06:44 UTC, pomegranited commented on docs/source/running_tasks.rst
> +#. I've started to put comments next to some parameters, please feel free to add in your own comments as well. Note that bash will get unhappy if you try to run these commands with those comments in
Since you're providing a working example of the commands below the annotated one, you can just move the commented parameters to a bulleted list or something, and then you could remove this comment entirely.

The inline comments are also difficult to read, since there's no syntax highlighting in the generated docs.

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +#. Tweak ``NUM_REDUCE_TASKS`` based on the size of your cluster. If the cluster is not being used for anything else a good rule of thumb is to make ``NUM_REDUCE_TASKS`` equal the number of available
Fair point, I've added a note here letting them know that's a "hadoop" concept that they should consult Hadoop docs to get more info.

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +#. There are a bunch of ``s3://`` paths listed below, but those could easily be replaced with ``hdfs://`` paths.
Good call. Done.

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +#. "credentials" files are json files should be stored somewhere secure and have the following format
Great suggestion, done!

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +#. I've started to put comments next to some parameters, please feel free to add in your own comments as well. Note that bash will get unhappy if you try to run these commands with those comments in
I like the idea of removing this line and moving the comments out into a bulleted list. I'm also trying to scrub out all first person from the doc. Great suggestions!

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +      --credentials s3://secure/path/to/result_store_credentials.json [See discussion of credential files above, these should be the credentials for the result store database to write the result to]
Done

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +The contents of a credentials file look something like this:
Ou - good call. Just removed the duplicate...

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +* This uses more up-to-date patterns.
Heh - good call. I just removed this comment...

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +    ImportEnrollmentsIntoMysql --local-scheduler \
Great idea, I added something like this to the notes.

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +Incremental implementation
@brianhw I'm hoping that since this doc is now committed with the code it can always reflect the code it is committed with. So as we make changes the docs evolve with the code. If someone wanted to know how it worked a while ago, they could simply pull the doc for the older version of the code by checking it out.

I think readthedocs actually supports this more elegantly by providing you with a menu at the bottom where you can switch between versions of the doc to see older stuff (for example: ficus or eucalyptus).

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +Incremental implementation
All of that said, the amount of re-writing here is beyond the scope of this ticket (simply migrating the doc from the github wiki) so I'll defer that to the next revision!

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +* This no longer supports a separate ``user-country-output`` parameter for intermediate data.  This is now written to a dated partition under ``(warehouse_path)/last_country_of_user/``.
Deleted this.

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +To load the historical enrollment events, you would need to first run:
Good catch, fixed!

2017-05-05 17:33 UTC, mulby commented on docs/source/running_tasks.rst
> +* Still a work in progress - erroneous events can make videos appear to be much longer than they actually are.
Heh - removed!

2017-05-05 17:37 UTC, merged