Add support for BigQuery event loading
openedx-unsupported/edx-analytics-pipeline pull request #437
Opened 2017-10-17 05:42 UTC by brianhw

Involves refactoring existing loading code into partition-based and non-partition-based tasks. 

Regular warehouse loading continues to use non-partition-based tasks.   The event loading uses partition-based tasks, for which overwrite is at the partition level rather than the table level.

2017-10-17 18:03 UTC, tobz requested changes

2017-10-17 18:03 UTC, tobz commented on edx/analytics/tasks/common/bigquery_load.py
> +        load_uri = self._get_load_url_from_destination(destination_path)
I feel like everything above, and including, this line for the method could be abstracted and used between the non-partitioning and partitioning job.

Maybe just take kwargs that correspond to table options and pass them through?

It's not huge, but, it does feel like a lot of duplication for what boils down to a single method to get the partition name, and passing a flag to enable it... everything else is effectively the same between the two versions.

2017-10-17 22:03 UTC, brianhw commented on edx/analytics/tasks/common/bigquery_load.py
> +        load_uri = self._get_load_url_from_destination(destination_path)
Yes, I agree.  When I started, there was a lot more different code, but I rearranged some of the base class as well, so the differences shrunk.  The only real remaining impediment is the adding of date as a parameter to the base class, but I think it should be there anyway (since it's actually used).

2017-10-17 22:05 UTC, brianhw commented on edx/analytics/tasks/common/bigquery_load.py
> +        load_uri = self._get_load_url_from_destination(destination_path)
Oh, but I think I would just parameterize it on a partition_type property.  If specified, then use that as a switch.

2017-10-18 19:02 UTC, tobz commented on edx/analytics/tasks/common/bigquery_load.py
> +        load_uri = self._get_load_url_from_destination(destination_path)
Yeah, whatever way you want to approach it, really.  The code duplication is really the only thing that makes me go "eeps".

2017-10-19 06:20 UTC, brianhw commented
Overwrite now works, and I've also gotten production to work (again).

2017-10-19 06:21 UTC, brianhw commented on edx/analytics/tasks/common/bigquery_load.py
> +        load_uri = self._get_load_url_from_destination(destination_path)
I think I've addressed that now.   There is a single class, differentiated by a property.

2017-10-24 13:21 UTC, HassanJaveed84 commented on edx/analytics/tasks/common/bigquery_load.py
> +                    partition = self._get_table_partition(dataset, table)
Wondering what we would get here if the partition does not exist yet ?

2017-10-24 13:29 UTC, HassanJaveed84 approved these changes
One question, otherwise LGTM 👍

2017-10-24 18:14 UTC, merged