WIP: Inspect traceback for handling end of output error.
openedx-unsupported/edx-analytics-pipeline pull request #440
Opened 2017-10-24 13:31 UTC by HassanJaveed84

2017-10-24 13:34 UTC, HassanJaveed84 commented on edx/analytics/tasks/common/mysql_load.py
> +            if "__iter__\n    self._finish()" in traceback_list[5]:
Do we want to simply this and only look for the _finish method call in the whole traceback, or do we want it to be really specific ?

Also I don't see any other place we can try catching the exception other than here.

2017-11-01 14:11 UTC, tobz approved these changes
LGTM, since we know it works in practice now 👍

2017-11-01 14:46 UTC, brianhw requested changes
Code looks good to me.  I would like to see a comment inside the except clause that briefly explains why we are doing this, because it's going to be really cryptic for anyone later picking up this code.

2017-11-01 14:47 UTC, brianhw commented
Oh, and love those commit comments..... : )

2017-11-02 11:40 UTC, HassanJaveed84 commented
Heh, squashed. Also added a comment explaining things. Does it look good ?

2017-11-02 13:59 UTC, brianhw approved these changes
LGTM.  👍

2017-11-03 05:44 UTC, brianhw commented
Turns out I'm running into similar issues on loading sailthru data to Vertica.  Looking forward to having this on master so I can rebase on it.

2017-11-06 14:24 UTC, merged