Fix HiveQueryToMysqlTask dependency in student_engagement workflow
openedx-unsupported/edx-analytics-pipeline pull request #462
Opened 2017-12-08 07:06 UTC by rao-abdul-mannan

2017-12-13 21:47 UTC, brianhw reviewed
Looks good!   I just suggest a few name changes, and potentially a little more use of the Record object you defined.   Then this will be ready to go!

2017-12-13 21:47 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    last_subsection_viewed = StringField(nullable=False, length=1000)
Do you know enough about these fields to be able to give them 'description' attributes?   At a minimum we could use the column names used in the previous task's get_column_names().

2017-12-13 21:47 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +        return StudentEngagementIntervalTypeRecord.get_hive_schema()
Note that this can also be used in StudentEngagementRawTableTask at the top of the file, best I can tell.

2017-12-13 21:47 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +class StudentEngagementIntervalTypeRecord(Record):
I might suggest moving this to the top of the file, especially if you use it in StudentEngagementTableTask.columns() and potentially in StudentEngagementTask.reducer() in the yield statement.  (For the latter, you can do something like in CourseEnrollmentSummaryTask in insights/enrollments.py, where a record is constructed, then output using "yield record.to_string_tuple()". )

2017-12-13 21:47 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +class StudentEngagementHiveTableTask(BareHiveTableTask):  # pragma: no cover
I would probaby just call this StudentEngagementTableTask, since that better matches the StudentEngagementPartitionTask and ...DataTask and so on.   The table that is above that is currently named StudentEngagementTableTask should probably get renamed to something else, perhaps StudentEngagementRawTableTask.

2017-12-14 07:29 UTC, rao-abdul-mannan commented on edx/analytics/tasks/data_api/student_engagement.py
> +class StudentEngagementHiveTableTask(BareHiveTableTask):  # pragma: no cover
Ok sounds good. I will rename them.

2017-12-14 07:32 UTC, rao-abdul-mannan commented on edx/analytics/tasks/data_api/student_engagement.py
> +    last_subsection_viewed = StringField(nullable=False, length=1000)
I will add the description and you can review it and let me know if it is not correct.

2017-12-14 07:32 UTC, rao-abdul-mannan commented on edx/analytics/tasks/data_api/student_engagement.py
> +        return StudentEngagementIntervalTypeRecord.get_hive_schema()
Ok I will make these changes

2017-12-14 12:44 UTC, rao-abdul-mannan commented on edx/analytics/tasks/data_api/student_engagement.py
> +class StudentEngagementIntervalTypeRecord(Record):
It makes sense considering the use case in `StudentEngagementTask.reducer() `. Alright, I'll update to reflect these changes.

2017-12-14 14:12 UTC, azafty468 approved these changes
Provided we get some field descriptions in here as Brian mentioned and we find some way to test this code (Acceptance Test or Release Candidate) I'm good with these changes.  Good job on your first PR!

2017-12-14 14:12 UTC, azafty468 commented on edx/analytics/tasks/data_api/student_engagement.py
> +    BareHiveTableTask, hive_database_name, HivePartition, HivePartitionTask, HiveQueryToMysqlTask, HiveTableFromQueryTask, HiveTableTask, WarehouseMixin
Just a small nit, can we remove the import of HiveQueryToMysqlTask as you have removed it from the code base.

2017-12-14 19:29 UTC, brianhw approved these changes
This looks good, Abdul!  I have a few wording suggestions for the field descriptions.  But after that, if you squash the commits and then it passes acceptance unit tests locally and acceptance tests on Jenkins, it should be fine to merge.  Let us know if you need help with how to squash and merge.

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +        description='Count of total problems attempted.'
Suggestion: "Count of unique problems attempted."   (I think the addition of 'unique' provides useful information here.)

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    )
If you want, you could put this all on a single line still.   I believe our line length is set to 120 characters, rather than 80.  (Likewise for other fields here.  And, well, I guess in general.)

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +        description='Id of course.'
Suggestion:  "Identifier of course run."

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +        description='Count of attempts on any particular problem.'
Suggestion: "Total count of problem attempts."

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    videos_played = IntegerField(description='Count of videos played.')
Suggestion: "Count of unique videos played."

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    problems_correct = IntegerField(description='Count of correct problems.')
Suggestion: "Count of unique problems that were answered correctly."

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    )
I'm fine with all the variable names using "forum_" -- but for the descriptions, let's go with the column names in the CSV output, that use "discussion" instead of "forum".   That should go for all seven fields above.

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    forum_responses = IntegerField(description='Count of problems attempted.')
Suggestion:  "Count of discussion responses created by user."    (Cut-and-paste error otherwise.)

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    Student Engagement information used to populate student_engagement_{interval_type} table.
nit:   "table" => "tables".

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +    end_date = DateField(description='')
Suggestion: "End date of the interval being analyzed."  or something similar.

2017-12-14 19:29 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +        )
nit:   add a newline. : )

2017-12-14 19:56 UTC, brianhw requested changes
One of the changes I had requested in the first round caused the code to break, as witnessed by the unit test failures.  (Acceptance tests also fail.)  I include the main fix, which I got from module_engagement.py.

2017-12-14 19:56 UTC, brianhw commented on edx/analytics/tasks/data_api/student_engagement.py
> +            end_date=date_grouping_key,
This needs to be changed to: 

> end_date=DateField().deserialize_from_string(date_grouping_key),

to get it to work.  There may possibly be similar changes in the unit tests, but glancing through doesn't look like there should be.

2017-12-14 19:59 UTC, brianhw commented
By the way, "squashing" involves using "git rebase".   You may want to take a look at documentation on that.   It looked like your "rebasing" to date involved performing merges from master instead of rebasing on master?   I wasn't sure from the commit messages.

2017-12-15 17:27 UTC, brianhw approved these changes
Looks good!   Ready to merge!   👍

2017-12-15 17:35 UTC, merged