fixing a bad record ordering for EnrollmentDailyRecord that was causi…
openedx-unsupported/edx-analytics-pipeline pull request #467
Opened 2017-12-22 04:21 UTC by azafty468

…ng fields to be incorrectly read

2017-12-22 05:29 UTC, brianhw approved these changes
LGTM. 👍

2017-12-22 08:56 UTC, brianhw commented
I also kicked off a manual acceptance test on Jenkins --  see edx-analytics-pipeline-acceptance-test-manual/1470.   The enrollment tests are still failing, but are closer.   Now they just differ in date format.  For example:

First has 1, Second has 0:  (u'2014-08-01', u'edX/Open_DemoX/edx_demo_course', 3, 4)
First has 0, Second has 1:  (datetime.date(2014, 8, 1), 'edX/Open_DemoX/edx_demo_course', 3, 4)

This is a side effect of switching to a Record, I suspect.  Abdul ran into a similar situation with student_engagement.

2017-12-22 09:17 UTC, brianhw requested changes
It would be good to fix the acceptance test first.   The problem is that these date fields are defined as StringField, but they should be defined as DateField.  The call to get_hive_schema() should return 'STRING', yes, but the call to .get_sql_schema()  should return 'DATE NOT NULL' as before, not 'VARCHAR(255) NOT NULL' which this produces.  It just happened to affect this table first (in validate_base()), but I believe all the other tables similarly defined would also have failed.

2017-12-27 16:05 UTC, brianhw commented on edx/analytics/tasks/insights/enrollments.py
>      at_end = BooleanField(description='An indicator if the learner is still enrolled in the course by this date.')
nit:   "by this date" => "at the end of this date"

2017-12-27 16:33 UTC, azafty468 commented on edx/analytics/tasks/insights/enrollments.py
>      at_end = BooleanField(description='An indicator if the learner is still enrolled in the course by this date.')
done and squashed back down to 1 commit

2017-12-27 16:34 UTC, azafty468 commented
merging

2017-12-27 16:53 UTC, brianhw approved these changes
Make this official.

2017-12-27 16:53 UTC, merged