Update Acceptence tests for data czar export key changes
openedx-unsupported/edx-analytics-pipeline pull request #475
Opened 2018-01-23 16:56 UTC by macdiesel

2018-01-23 21:25 UTC, brianhw reviewed
Few questions.

2018-01-23 21:25 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_database_export.py
> +            org_config_file.write(config_text)
Should this be org_config_text?

2018-01-23 21:25 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_database_export.py
> +
Is this missing environment=self.ENVIRONMENT that was used before?

2018-01-23 23:23 UTC, iloveagent57 requested changes
Looks good, other than the `org_config_text` thing that Brian pointed out, which I think will make this do the wrong thing.

2018-01-23 23:23 UTC, iloveagent57 commented on edx/analytics/tasks/tests/acceptance/test_database_export.py
> +        config_text = env_config_text.format(
Maybe better to call the `env_config_text`.

2018-01-23 23:23 UTC, iloveagent57 commented on edx/analytics/tasks/tests/acceptance/test_database_export.py
> +            env_config_file.write(config_text)
...and change it here.

2018-01-23 23:23 UTC, iloveagent57 commented on edx/analytics/tasks/tests/acceptance/test_database_export.py
> +            org_config_file.write(config_text)
I think it should be.

2018-01-23 23:24 UTC, iloveagent57 commented
...err, well, I guess I was looking at a test file, so "doing the wrong thing" may be over the top, but you get the idea...

2018-01-24 19:28 UTC, macdiesel commented
My apologies, this was sloppy, won't happen again.

Ready for re-review.

2018-01-24 19:38 UTC, brianhw reviewed
Another question.

2018-01-24 19:38 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_database_export.py
> +        self.write_exporter_config(org_id, course_id, env_config_file_path)
Isn't this supposed to have two config files?

2018-02-02 02:11 UTC, brianhw commented
I assume this PR should be included as a sub-task of DE-414.   The acceptance tests in master are still breaking for test_database_export.ExportAcceptanceTest.test_database_export.

2018-02-06 16:01 UTC, macdiesel commented
Codecov says these lines are not exercised during the test. Is s3 available in travis to run these tests? If not I can mark these areas as # pragma: no cover and merge.

2018-02-07 16:06 UTC, azafty468 approved these changes
👍

2018-02-07 16:08 UTC, azafty468 commented
I do not belief S3 is available for Travis but I'm not 100% positive

2018-02-09 16:07 UTC, merged