Use spark task in production jobs
openedx-unsupported/edx-analytics-pipeline pull request #485
Opened 2018-03-13 13:59 UTC by rao-abdul-mannan

Purpose of this PR is to convert an existing hadoop task to spark & use it in production for atleast a month and see how it performs as well as figure out any issues encountered during this trial run.  
Related ticket DE-573

2018-03-13 14:25 UTC, brianhw commented
Just noting that the travis builds failed:   "ERROR: /edx/app/analytics-pipeline/edx/analytics/tasks/insights/tests/test_user_activity.py Imports are incorrectly sorted."

2018-03-13 14:30 UTC, rao-abdul-mannan commented
@brianhw I sorted it again with isort but it did not go away

2018-03-13 16:17 UTC, brianhw requested changes
I'm not sure if this is really going to master, or if the proposal was to run this in its branch.  If just the latter, then most of my nit-picking comments can be ignored.  (I have different standards for master than for experimental branches.)  

The main question I have is scope -- should this include as well all the Hive replacement that I thought you wrote?  I only see the initial history task included here.  

But if we were to run the hive replacement workflow, then I think it should be defined separately and pulled into a separate file, and possibly inheriting and overriding some original classes as necessary to be more DRY about it.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +    import zipfile
Do we need this here?   It's already imported at the top of the file.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        # Ensure any entry points and other egg-info metadata is also transmitted along with
nit:  s/is/are/

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +            .add("session", StringType(), True)
So there are a bunch of schema entries here that we do not use for any of our workflows.   I would suggest that this base version be more minimal.   If there are other entries that are needed in special cases, this can be overridden, or added to using a super() call.  

I would suggest that all we need here are:  user_id, course_id, org_id from context, and username, event_type, ip, event_source, context, and time from the base level.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        from pyspark.sql.types import StructType, StringType
Should this be at the top of the file?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        from pyspark.sql.functions import to_date, udf, struct, date_format
should this be at the top of the file?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +
nit:  either remove this newline, or add one after other schema definitions.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +    def get_event_log_dataframe(self, spark, *args, **kwargs):
This could use a docstring, to indicate at least what kind of object "spark" is that is being passed in.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +    Wrapper for spark task
nit:  end doc sentences with a period.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +    always_log_stderr = False  # log stderr if spark fails, True for verbose log
Is this something that should be configured, or is it to be changed in code by someone trying to debug something?  It might be worth a comment (on the line before).

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        from pyspark.sql import SparkSession, SQLContext, HiveContext
Should these be moved to the top of the file now?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        Spark code for the job
nit: end with a period.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        self._hive_context = HiveContext(sc)
Should this be commented out for now?  I don't believe we are using Hive in Spark, are we?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/util/constants.py
> +    """Constants for predicate labels."""
This doesn't explain enough to me.  Having moved it out of user_activity means it has much less context.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/insights/user_activity.py
> +            yield UserActivityTaskSpark(
I'm not sure if the purpose of this PR is to merge the code to master, but I do not want to change the default behavior of master by merging this in as-is.  We should be able to run the two workflows side-by-side, the spark and the hive.

Perhaps the spark user-activity workflow can be put in a separate file, and the relevant sequence of tasks can be recreated by overriding the requires methods of the dependent tasks.  If so, we could move the user-activity part of spark_utils into that file. 

But wait, I thought that you had implemented an alternative more of the workflow than just this one task -- that you had also replaced the Hive calculations with Spark SQL.  Am I misremembering?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/util/spark_util.py
> +    Don't pass whole event row to any spark UDF as it generates a different output than expected
I don't understand this.  (Also nit: end sentence with period.)

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/util/spark_util.py
> +    # return 'test'
I assume this line should be removed?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/util/spark_util.py
> +    # TODO : make it work with url as well
When does this need to be done?   I'm guessing for event exports.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/util/spark_util.py
> +    Get value from event dict by key
nit: end with period.   
But is 'event' here a dict, or some other object?   If it were really a dict, this wouldn't be necessary, but it's something else.   It would be good to note here what that something is.....

But this code may not be called at present anyway, because the code in get_course_id() that called it is commented out?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/util/spark_util.py
> +    Don't pass whole event row to any spark UDF as it generates a different output than expected
I don't understand this.  (Also nit: end sentence with period.)

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/insights/user_activity.py
> +class UserActivityTaskSpark(EventLogSelectionMixinSpark, WarehouseMixin, SparkJobTask):
As mentioned below, maybe this should move to a separate file, and define an entirely separate workflow?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +
Is this method doing anything?   It's not returning configuration as a dict.  nit: no blank line.  End comments with period.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/insights/tests/test_user_activity.py
> +from mock import Mock, call
Not clear on the reorganization here, but it breaks the isort test in the quality build.  We separate out python imports, third party imports, and then our local code imports into separate groups.  Presumably the ddt and mock imports should go back where they were.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/insights/user_activity.py
> +from edx.analytics.tasks.common.spark import EventLogSelectionMixinSpark, SparkJobTask
I see, so this may answer my question about imports.  If we put them at the top of common/spark.py, and this is included in our regular code, then we're making *everything* dependent on spark code.   I think it should be pulled out into a separate workflow.

2018-03-13 16:17 UTC, brianhw commented on config/devstack.cfg
> +executor-cores=1
nit: Add newline.

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +            options = task_config
Should these three lines above be removed?   Was it an experiment that didn't work out?

2018-03-13 16:17 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        List of options that needs to be passed to spark task
Where does this get called?   Also, maybe provide more explanation as to why the call to Luigi's configuration is being done here.  It's not clear to me why we couldn't put this logic into _load_internal_dependency_on_cluster().

2018-03-14 11:09 UTC, rao-abdul-mannan commented on edx/analytics/tasks/util/spark_util.py
> +    # TODO : make it work with url as well
This will be needed when running spark based tests.

2018-03-14 11:10 UTC, rao-abdul-mannan commented on edx/analytics/tasks/util/spark_util.py
> +    Don't pass whole event row to any spark UDF as it generates a different output than expected
I'll remove the second line as it is confusing here.

2018-03-14 11:19 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        List of options that needs to be passed to spark task
Luigi configuration cannot be retrieved directly inside a spark job. Due to this issue, any configuration that is required by spark job is provided as a command line argument to spark-submit. This method is called directly by luigi to map custom parameters to arguments. 

This method along with get_luigi_configuration aren't used in this particular workflow but will be used for other spark tasks as used in #476

2018-03-14 11:30 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +            options = task_config
No, let me explain these functions in more detail. 
Since luigi configuration cannot be retrieved inside spark task, any spark task which will need to access those configuration should overwride get_luigi_configuration method and return required luigi configurations as a dictionary. 

app_options method will  then convert these dictionary configurations and pass it to spark task as command line arguments via spark-submit. Again, these methods aren't used in this task but they will be used later with other spark tasks.

2018-03-14 11:34 UTC, rao-abdul-mannan commented on edx/analytics/tasks/insights/tests/test_user_activity.py
> +from mock import Mock, call
Isort fails the test in both cases, whether they are organized this way or not. Though when sorted on local, this is how isort rearranges it.

2018-03-14 11:36 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +
This method should be overridden in spark jobs if they need to access luigi's configuration.

2018-03-14 11:40 UTC, rao-abdul-mannan commented on edx/analytics/tasks/insights/user_activity.py
> +class UserActivityTaskSpark(EventLogSelectionMixinSpark, WarehouseMixin, SparkJobTask):
I think its more manageable and easy to reference their counterpart hadoop job if new spark jobs are placed near them and in future it will be easy to just remove these classes entirely once we are done with them.

2018-03-14 13:00 UTC, rao-abdul-mannan commented on edx/analytics/tasks/util/spark_util.py
> +    Get value from event dict by key
It is called to get the course id from the event context. I have updated the docs about the object type

2018-03-14 13:01 UTC, rao-abdul-mannan commented on edx/analytics/tasks/util/spark_util.py
> +    # return 'test'
Yup, removed it

2018-03-14 13:10 UTC, rao-abdul-mannan commented on edx/analytics/tasks/util/spark_util.py
> +    Don't pass whole event row to any spark UDF as it generates a different output than expected
Perhaps name is confusing here, so i'll rename it. It is basically spark equivalent method of get_predicate_labels.

2018-03-14 13:12 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        self._hive_context = HiveContext(sc)
Right.

2018-03-14 13:16 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        from pyspark.sql import SparkSession, SQLContext, HiveContext
No, we can't move it to the top since it is imported in user_activity file which still has hadoop/hive jobs and it will error it when running those jobs.

2018-03-15 12:55 UTC, closed without merging