ENT-978 Add user country code and last activity date in enterprise en…
openedx-unsupported/edx-analytics-pipeline pull request #504
Opened 2018-05-14 11:24 UTC by zubair-arbi

…rollment hive table

* Add fields `user_country_code` and `last_activity_date` in `EnterpriseEnrollmentRecord` table.
* Update `insert_query`to populate above fields during `EnterpriseEnrollmentDataTask`

Remaining Task:
* Cannot add/populate field `country_name` as we are using django-countries which provide method for getting country name against the provided country code. We cannot do this with such ease in SQL. One way we can try is using manual dump for countries along with code and name.

2018-05-14 12:20 UTC, zubair-arbi commented
@brittneyexline @georgebabey Please let me know if this is what we wanted for ENT-978. I am unable to get user country name which I mentioned in the PR description.

2018-05-16 02:25 UTC, georgebabey requested changes
You'll also need to update the acceptance tests to include these new fields fields, or they will also fail:
edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py

2018-05-16 02:25 UTC, georgebabey commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +                    course.catalog_course AS course_key,
Order matters here so be careful moving course_key. This order here needs to match the order in the fixture data here or else the acceptance tests will fail: edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py

See this PR from @mattdrayer https://github.com/edx/edx-analytics-pipeline/commit/16780bdba521035326d492d29cd156a8e843f0e9

2018-05-16 02:29 UTC, georgebabey commented
Just realized we should call this `last_activity_timestamp` to align with the other datetime fields: `enrollment_created_timestamp`,  `passed_timestamp`, `user_account_creation_timestamp`

2018-05-17 19:18 UTC, brianhw commented
A few observations:
* You have added references to two additional tables in your Hive query, but you don't do what is needed to load that data into Hive.   In particular, the EnterpriseEnrollmentDataTask.requires() method should include tasks that make this happen.  That includes ImportAuthUserProfileTask() (to load auth_userprofile into Hive), and something to load user_activity_by_user into Hive.  
* The loading of user_activity_by_user into Hive is a little subtle.   You would use UserActivityTableTask (as defined in insights/user_activity.py), but you must pass in a parameter value for overwrite_n_days of zero, so that there is no attempt to recalculate any data.  This would simply use whatever data is currently available on the machine.  
* Your join "ON enterprise_user.user_id = user_profile.id" should be "ON enterprise_user.user_id = user_profile.user_id" instead? 
* In testing, you need to define user_activity_by_user fixture differently.   The data is not read from an LMS database, so there is no need to define such a table.  You have to write out files to the right warehouse_path location, since it is an intermediate output of a different pipeline job.   An example of this is CourseBlocksPartitionTaskAcceptanceTest.copy_hive_input() in test_course_blocks.py, though that's just the first I found.    You may want activity for more than one day.
* You can run acceptance tests on the test_ci server, using the ad-hoc manual job and putting in your branch and the name of the test (i.e. test_enterprise_enrollments).  Let me know if you need permission and don't have it.   Brittney and George do as well.

2018-05-21 19:42 UTC, georgebabey approved these changes
Updates look good but let me coordinate with @brianhw  to determine the best process for rolling these pipeline changes out before merging

2018-05-22 05:39 UTC, brianhw commented
I'm glad you tried to run the acceptance test.  It looks like it failed because of an extra character in one of your fixture files.  

Also, the Travis builds are failing due to an issue with ordering of includes:  
```
isort --check-only --recursive edx/
ERROR: /edx/app/analytics_pipeline/analytics_pipeline/edx/analytics/tasks/enterprise/enterprise_enrollments.py Imports are incorrectly sorted. 
```

2018-05-24 11:45 UTC, zubair-arbi commented
@brianhw Please have another look on the changes now.
Can you please tell why acceptance tests on jenkins failed: http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/1566/console

2018-05-24 20:24 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/fixtures/input/enterprise/auth_userprofile.sql
> +    ('8', 'Test User4', '', 'course.xml', '', '', '1989', 'f', '', '', '', 'US', '', '1', NULL, NULL, '14'),
So the problem with acceptance tests seems to be with loading this file.   At the bottom of the log, there is:
```
11:10:35 edx.analytics.tasks.tests.acceptance: DEBUG: Executing SQL fixture /var/lib/jenkins/jobs/edx-analytics-pipeline-acceptance-test-manual/workspace/analytics-tasks/edx/analytics/tasks/tests/acceptance/fixtures/input/enterprise/auth_userprofile.sql on acceptance_import_test_7d1cbdd16cac88a0b607536ba10f891d
```
And under the traceback, "11:10:35 ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 8".  

This is the only thing that really looks wrong.  It should end with a semi-colon, not a comma.

2018-05-25 11:22 UTC, zubair-arbi commented
@brianhw Thanks for pointing to syntax issue in fixture file. It look like `EnterpriseEnrollmentDataTask` failed now.
**Console log:** http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/1567/console

2018-05-25 12:58 UTC, rao-abdul-mannan commented
@zubair-arbi Error seems to be 
`Failed to recognize predicate 'date'. Failed rule: 'identifier' in table or column identifier`
in the EnterpriseEnrollmentDataTask, which could be due to no whitespace being used in table name and alias `social_auth_usersocialauth`
https://github.com/edx/edx-analytics-pipeline/blob/3f3de316aae718348fc991343805dbf7c7c795c3/edx/analytics/tasks/enterprise/enterprise_enrollments.py#L176

2018-05-25 15:10 UTC, rao-abdul-mannan commented
Sorry about my earlier comment. 
So I have found 2 issues that **could** be the failure reason.
-  Due to hive reserved keywords, table & column names in the query should be wrapped in back ticks ( ` )

    e.g. date should be `date` in subquery
- `last_activity_timestamp` is a timestamp field and query is writing Date to it.

2018-05-25 17:01 UTC, brianhw reviewed
Following up on Abdul's comments, here are some more specific locations and fixes.

2018-05-25 17:01 UTC, brianhw commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +    last_activity_timestamp = DateTimeField(description='')
I think that if you are storing values like "2018-05-18", you may need to use a DateField here instead of a DateTimeField.    I don't know if that would involve changing the name of the field as well.   Or if we need to find a different way of getting the actual timestamp of the last activity, instead of merely the date.

2018-05-25 17:01 UTC, brianhw commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +                        MAX(date) AS latest_date
This may be the line that requires date to be back-quoted.

2018-05-29 03:47 UTC, brianhw commented
Looks like it needs a rebase....

2018-05-29 03:50 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +                   'user_country_code', 'last_activity_timestamp']
You probably need to update the field name here as well.

2018-05-29 16:13 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +            os.path.join(self.data_dir, 'input', 'internal_reporting_user_activity'),
You are using a different file for user_activity here.   This has a different set of users than you have defined in auth_userprofile.  You define a user_activity_by_user fixture file which uses matching user_ids.  You could point to that here.

2018-06-05 09:32 UTC, zubair-arbi commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +            os.path.join(self.data_dir, 'input', 'internal_reporting_user_activity'),
@brianhw I have verified that users defined in `user_activity_by_user` fixture file matches in `user_ids` and also the `upload_file` path matches the hive path `edx.analytics.tasks.insights.user_activity.UserActivityTask#output_path_for_key`. Still `last_activity_date` values are empty.

2018-06-08 05:10 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +            os.path.join(self.data_dir, 'input', 'internal_reporting_user_activity'),
RIght.   But this line uploads 'internal_reporting_user_activity' to the warehouse_path/'user_activity_by_user' location, rather than the 'user_activity_by_user' that you defined earlier.   You need to change this line to os.path.join(self.data_dir, 'input', 'user_activity_by_user'),

2018-06-11 12:10 UTC, zubair-arbi commented
@brianhw @rao-abdul-mannan I have updated the file path according to your suggestions now acceptance tests are passing with success http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/1592/console
I have rebased and squashed the commits. Please have a final look on the changes.

2018-06-11 15:29 UTC, brianhw approved these changes
If the acceptance tests pass now, then 👍 .

Keep in mind, however, that there are two issues with merging to master.   One is that there are two PRs, and that only one can go to master.  The second one to merge will have to be rebased (with merge conflicts resolved), and re-tested.   The other is that the main job runs off of master, so it would break.   I'll suggest to Enterprise folks that they run off of our release instead of master.

2018-06-11 16:02 UTC, brianhw commented
I've changed the "enterprise-enrollment" job to run off of origin/release instead of origin/master, so there is less risk to production to have this merge to master.   Same with #512 .

2018-06-12 08:21 UTC, zubair-arbi commented
@brianhw the acceptance tests again passed with success after rebase http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/1594/console

2018-06-12 10:12 UTC, merged

2018-06-12 10:12 UTC, zubair-arbi commented
@saleem-latif I have merged this branch please rebase your branch (https://github.com/edx/edx-analytics-pipeline/pull/512) now.