WIP:  Add basic Spark support.
openedx-unsupported/edx-analytics-pipeline pull request #516
Opened 2018-06-11 05:35 UTC by brianhw

This is a first step towards adding basic Spark support, independent of work done on Insights workflows.   Two main things this PR aims to provide are options support and dependency loading.   And these still need more work.  I am thinking of moving the dependency loading to be more similar to how the hadoop tasks handle it.   I think Abdul had ideas about improving options, but I don't remember what they were.   I would like to land this (and release it) before the Hawthorn release is tagged.

2018-06-11 10:20 UTC, rao-abdul-mannan commented on config/devstack.cfg
> +executor-cores=1
Though edx_egg_files is not required in vagrant devstack, but it should include a small note here explaining about its usage/importance while running it on a multi-node cluster ?

2018-06-11 10:20 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +    def get_luigi_configuration(self):
Though I am still hesitant about loading luigi configuration this way before we merge spark work into master branch, but since we haven't worked on the other solution so I guess we don't have a choice.

2018-06-11 10:20 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        import cjson
`cjson` package doesn't work on spark standalone cluster and I guess it won't work on yarn cluster either. I tried creating its egg but failed. Have you tried this in docker or yarn ?

2018-06-11 10:20 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +from edx.analytics.tasks.util.url import get_target_from_url, url_path_join
L13-18 are unused imports

2018-06-11 16:11 UTC, brianhw commented on config/devstack.cfg
> +executor-cores=1
Hmm.   I just blindly brought this over from your branch, and had assumed that this was for docker.  (But that's what luigi_docker.cfg is for.)  I think I'll just take this out, because we don't currently support Spark on vagrant devstack.  (And add more comments in luigi_docker.cfg.)

2018-06-11 16:19 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +from edx.analytics.tasks.util.url import get_target_from_url, url_path_join
Oops.  Good catch.

2018-06-11 16:19 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        import cjson
This code worked for me on my hackathon, both on docker and EMR.  But I didn't make any use of most of these, since I was not running on events.   I want to pare this down to the minimum (i.e. edx, luigi, stevedore), and allow other tasks to add imports to this list as we do for Hadoop jobs.   I also want to only load the egg files that are requested, so I would like to change the list to a dict in the config file for that.

2018-06-11 16:19 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        # TODO: pull definition of __name__ out into a class property.
I'm still hoping to make this change too.

2018-06-14 04:09 UTC, brianhw commented
This is ready for another (hopefully final) review.

2018-06-14 11:14 UTC, rao-abdul-mannan requested changes

2018-06-14 11:14 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +    subprocess, while others will be executed in the main process (that contains Luigi).
This note is helpful especially which functions are executed within spark and luigi.

2018-06-14 11:14 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        Return Luigi configuration needed for this Spark task, as a dict.
I have another ( a bit clean ) solution for luigi ( for now ). 
Instead of user fetching each configuration value, that they need, in the base class method,  why not we allow user to just return a dict of {"sections_names"=>"option_name"} instead and then fetch all these values from that dict in app_options method ?
I think it will be a lot cleaner that way where they just specifiy which values they would need in their spark task and they can get those values from spark_get_config_from_args().

2018-06-14 11:14 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        from configuration if the command line is not used.
It is not just to override the configuraton values, it allows user to specify extra arguments which luigi has not provided support yet and there are dozens of such properties. So instead of specifying all of them in configuration, they have added a generic option which user can overwrite to add new configuration.
e.g. conf=spark.default.parallelism=100|spark.sql.shuffle.partitions=200 ( both these properties & many more cannot be added directly in configuration section with their own name ).

2018-06-14 11:14 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +            self._spark_load_internal_dependency_on_cluster(*args)  # load packages on EMR cluster for spark worker nodes
Comment needs to be reworded. Its not just for **EMR** anymore since we now have standalone cluster in docker devstack.

2018-06-14 11:14 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        Loading of packages via a single zipfile is adequate for most packages.  However, it is not adequate for
Shouldn't we need to define some base packages that will at least enable pyspark to run python code on worker nodes ? 
For extra packages, we can ask user to define them but having them specify basic package list is redundant + hectic for anyone to figure it out.

2018-06-14 11:43 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        from configuration if the command line is not used.
Right.  But this is allowing conf to be defined on the command line, rather than requiring that it be defined in the Luigi configuration file.  Is there a specific way in which the wording of this could make that clearer?

2018-06-14 11:44 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +            self._spark_load_internal_dependency_on_cluster(*args)  # load packages on EMR cluster for spark worker nodes
Good point.

2018-06-14 11:53 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        Loading of packages via a single zipfile is adequate for most packages.  However, it is not adequate for
No.  Nothing needs to be defined here in order to get generic Spark python code to run on worker nodes.   I did my hackathon project using Spark ML and had all of this commented out.  It is only necessary to add things here when the UDFs one is using require more custom imports.    I tested this mechanism by using get_org_id_from_course_id() in a udf, and found that I needed edx, stevedore, bson, opaque_keys, and optionally ccx_keys.  (If I used a course_id that was ccx-based, the org would be found or would be Null depending on whether ccx_keys were loaded -- as expected.)    But I think we will want another class on top of SparkJobTask that is used as the basis for all the event-based processing that the Insights tasks do, and that should define the packages that it needs for its event parsing and processing.  But that should be a separate class from this base class.

2018-06-14 11:54 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +    subprocess, while others will be executed in the main process (that contains Luigi).
I found that knowing where something was run was one of the major challenges of understanding the code, so I wanted to make it a little easier for others.

2018-06-14 12:09 UTC, brianhw commented on edx/analytics/tasks/common/spark.py
> +        Return Luigi configuration needed for this Spark task, as a dict.
I'm not understanding.  Users are already providing a dict, so you're suggesting a change in the convention of how that dict is structured.   Are you just suggesting that another level be added to the dict, so that its keys are section names, and within each section is another dict with key-value pairs?  (I didn't understand what {"sections_names"=>"option_name"} meant.)  And then spark_get_config_from_args() would have an args and key argument as it currently does, but also an additional section argument?  

Also, the first goal of this is to get configuration across the spark-submit boundary.   I am assuming that this mechanism does not work within UDFs.  I am assuming that any values need to be pulled out in the spark_job() level, and explicitly passed to UDFs.

2018-06-14 12:12 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        Loading of packages via a single zipfile is adequate for most packages.  However, it is not adequate for
Just wanted to clarify, thats good to know if it is working fine.

2018-06-14 12:20 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        from configuration if the command line is not used.
I just to make sure that if by reading these comments + the description of spark_conf luigi parameter, users will be able to understand that they can specify extra spark configurations via this option well.

2018-06-14 12:23 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        from configuration if the command line is not used.
if it does, then i'm okay with it.

2018-06-14 12:31 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
> +        Return Luigi configuration needed for this Spark task, as a dict.
`app_options` method maps user supplied configuration ( get_task_configuration_from_luigi )  to spark-submit args. `app_options` is called from luigi & not from spark hence we can get luigi configuration values directly here. 
I'm saying we can have this function return something like a dict ( {'interval': 'calendar'}, option name is key, section is value ) and then get their values inside  `app_options` method.

2018-06-15 01:39 UTC, brianhw commented
As requested, I rewrote the configuration handoff between Luigi and Spark, so it is a lot simpler and more intuitive now.   On the Luigi side, a task requests configuration values to save by providing section and parameter-name, and on the Spark side, the task can request the configuration values by providing the same section and parameter-name to get the configuration values returned.    Ready for review again. : )

2018-06-19 15:28 UTC, rao-abdul-mannan requested changes
Only comment needs an update, apart from that everything looks good.

2018-06-19 15:28 UTC, rao-abdul-mannan commented on edx/analytics/tasks/common/spark.py
>          This is the mirror of get_task_configuration_from_luigi.
Comment needs to be updated => **This is the mirror of request_configuration_from_luigi**

2018-06-19 15:30 UTC, rao-abdul-mannan commented
LGTM 👍

2018-06-19 15:31 UTC, rao-abdul-mannan approved these changes

2018-06-19 15:57 UTC, azafty468 approved these changes
Code looks good, I'm a 👍

2018-06-19 19:16 UTC, merged