WIP --- ENT-1232
openedx-unsupported/edx-analytics-pipeline pull request #534
Opened 2018-10-17 12:33 UTC by asadiqbal08

WIP FOR TESTING --- Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

2018-10-23 09:22 UTC, saleem-latif reviewed
Looking good so far

2018-10-23 11:30 UTC, asadiqbal08 commented
@brittneyexline Can you please look around the general changes in this PR?

2018-10-23 14:29 UTC, brittneyexline reviewed
this is a solid start - next steps would be to incorporate testing your changes in the acceptance test (https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py) and run the acceptance test.

I haven't worked in this repo recently, but I believe this repo can now be set up in docker and you can run the acceptance tests there. In the past, I have run the acceptance tests on the data team's jenkins server (http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/), but you will need access from Brian Wilson for that.

Also, keep in mind that you will have to make changes to the data api (https://github.com/edx/edx-enterprise-data/tree/master/enterprise_data) to include the unenrollment timestamp.

2018-10-24 13:06 UTC, asadiqbal08 commented
Thanks @brittneyexline . Yes I have requested the Brian for the access. In parallel, I did the corresponding changes in enterprise data repo [HERE](https://github.com/edx/edx-enterprise-data/pull/76)

2018-10-25 09:52 UTC, asadiqbal08 commented
@brittneyexline I have run the acceptance tests on the data teams's jenkins server. Build seems me successful. You can take a look on the build parameters [HERE](http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/1648/)

And let me know is anything else is required in the PR to add or go ahead with merge ?

2018-10-25 14:41 UTC, brittneyexline reviewed
could you update the fixtures and acceptance test to actually pull in an unenrollment timestamp value?

2018-10-30 11:55 UTC, asadiqbal08 commented
@brittneyexline can you guide me why a particular acceptance test is failing [HERE](http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/1650/testReport/junit/edx.analytics.tasks.tests.acceptance.test_enterprise_enrollments/EnterpriseEnrollmentAcceptanceTest/test_enterprise_enrollment_table_generation/)
Either it seems to wrong with code changes ?

2018-10-30 17:37 UTC, brittneyexline commented
@asadiqbal08 it looks like the acceptance test is failing because `CourseEnrollmentEventsTask` failed.
```
Scheduled 67 tasks of which:
* 18 present dependencies were encountered:
    - 1 ExternalURL(url=s3+https://edx-analytics-test-data/credentials/acceptance-db.json)
    - 2 PathSelectionByDateIntervalTask(...)
    - 1 PullDiscoveryCourseRunsAPIData(...)
    - 14 UncheckedExternalURL(...)
* 43 ran successfully:
    - 1 CourseDataTask(...)
    - 1 CourseEnrollmentSummaryTableTask(warehouse_path=s3://edx-analytics-test-output/automation/f2c7086f821391d1ddb741986c718f7e/EnterpriseEnrollmentAcceptanceTest/warehouse)
    - 1 CoursePartitionTask(...)
    - 1 CourseTableTask(warehouse_path=s3://edx-analytics-test-output/automation/f2c7086f821391d1ddb741986c718f7e/EnterpriseEnrollmentAcceptanceTest/warehouse)
    - 1 EnterpriseEnrollmentHivePartitionTask(warehouse_path=s3://edx-analytics-test-output/automation/f2c7086f821391d1ddb741986c718f7e/EnterpriseEnrollmentAcceptanceTest/warehouse, date=2016-09-08)
    ...
* 1 failed:
    - 1 CourseEnrollmentEventsTask(...)
* 5 were left pending, among these:
    * 5 was not granted run permission by the scheduler:
        - 1 CourseEnrollmentSummaryPartitionTask(...)
        - 1 CourseEnrollmentSummaryTask(...)
        - 1 EnterpriseEnrollmentDataTask(...)
        - 1 EnterpriseEnrollmentMysqlTask(...)
        - 1 ImportEnterpriseEnrollmentsIntoMysql(...)

This progress looks :( because there were failed tasks
```
Since you introduced this new dependency, the enterprise enrollments acceptance test hasn't set up what is necessary for the task in a test environment. Take a look at https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/tests/acceptance/test_enrollments.py to see what that task needs set up. You'll also have to change the expected data returned in the acceptance to include the new field's data, not just add it to the top level fields.

2018-11-05 14:41 UTC, asadiqbal08 commented
@brianhw I am working on that PR from last couple of days. Can you please look around the changes in it ? one of the existing test `test_enterprise_enrollment_table_generation` is failing. I tried to provide the data that seems to me required for the execution. You can look on the failed build [HERE](http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/1670/testReport/edx.analytics.tasks.tests.acceptance.test_enterprise_enrollments/EnterpriseEnrollmentAcceptanceTest/test_enterprise_enrollment_table_generation/?auto_refresh=false)

2018-11-05 17:35 UTC, brianhw commented
@asadiqbal08 Adding a dependency on Enrollment is pretty squirrelly stuff -- good work so far.  Looking at the acceptance test output failure you pointed to, the task that failed was CourseEnrollmentEventsTask, which failed because it did not find any input tracking log files in the specified interval:  interval=2018-10-22-2018-11-05.   (There is a warning "Directly processing files since 0 inputs are less than the threshold 500" that is pretty cryptic, but indicates the problem.)  You have loaded a course_enrollment_summary fixture, dated to 2016-09-08, and the hope was that it would be enough to satisfy the dependency on CourseEnrollmentSummaryPartitionTask.   However, the CourseEnrollmentSummaryTask inherits from CourseEnrollmentTask, which causes the output to be deleted and recalculated if it is not "complete" (in the run() method), and the complete() method in turn checks for the presence of a "marker" file named "_SUCCESS" next to the data file you output.   So, create that marker file as part of your setup.  Also, the interval that gets passed for the test must end in the same date as the location of the course_enrollment_summary, so the interval passed in this test should end with 2016-09-08, not with today's date.

2018-11-05 19:15 UTC, brianhw commented
Hmm, as I think about this, I'm wondering if we need to decouple this from the Enrollment workflow.  I am concerned that if this job is run before enrollment completes for the current day, then it will try to calculate values rather than using the values that were calculated in the enrollment workflow and thus prevent the enrollment workflow from doing some of its calculation.  

In particular, as we saw above, if the per-user enrollment summary data is not present, the enterprise workflow will try to run CourseEnrollmentEventsTask with no overwriting.  I think that means that it won't include yesterday's events.   So I think we really want this to use an external task that somehow loads the data but would fail if it were missing, rather than running  CourseEnrollmentEventsTask to try to calculate missing data.

2018-11-05 19:18 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +            '--marker', self.marker_path,
I don't know what this particular argument does, but I don't think it has any effect on the workflow.

2018-11-05 19:40 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        )
Create a file in  url_path_join(
                self.warehouse_path,
                'course_enrollment_summary',
                'dt=' + self.DATE, '_SUCCESS')

2018-11-05 19:40 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +            '--marker', self.marker_path,
So I would remove it.

2018-11-06 12:17 UTC, asadiqbal08 commented
@brianhw I did the changes as u suggested and re run the test but now it is complaining about the `--interval` parameter in [logs](http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/1683/testReport/edx.analytics.tasks.tests.acceptance.test_enterprise_enrollments/EnterpriseEnrollmentAcceptanceTest/test_enterprise_enrollment_table_generation/). 
`launch-task: error: unrecognized arguments: --interval 2014-07-30-2016-09-08`
Does it require to introduce this parameter in some other places / repos ? 
Can you take another look around the logs and code changes ?

2018-11-06 21:02 UTC, brianhw commented
One quick point:  @brittneyexline noted that she thought "this repo can now be set up in docker and you can run the acceptance tests there."   I just wanted to confirm that this is true.  Look for the analytics section in the docker repo's readme.

2018-11-06 21:24 UTC, brianhw requested changes
Here is my feedback.  Hope it makes sense.

2018-11-06 21:24 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        self.upload_tracking_log(self.INPUT_FILE, datetime.date(2014, 7, 30))
I don't understand why you need this.

2018-11-06 21:24 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +    INPUT_FILE = 'enrollment_trends_tracking.log'
I don't understand why you need this.

2018-11-06 21:24 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        self.marker_path = url_path_join(self.test_out, 'marker-{}'.format(str(time.time())))
I don't understand why you need this.

2018-11-06 21:24 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        )
You needed to create the _SUCCESS file *in addition* to the copy of course_enrollment_summary that you had there before.   One is the data, the other is the marker that the data is complete.   Note that you could set self.marker_path = url_path_join(self.warehouse_path, 'course_enrollment_summary', 'dt=' + self.DATE, '_SUCCESS'), and then create it.  

But, once you use ExternalCourseEnrollmentSummaryPartitionTask, you no longer need this marker file.

2018-11-06 21:24 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        #self.validate_marker(self.marker_path)
wrong value of marker_path

2018-11-06 21:24 UTC, brianhw commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +            CourseEnrollmentSummaryPartitionTask(
I think this needs to change.   You need to create a modification of this class that does not depend on CourseEnrollmentSummaryTask, but instead points to the output of that task.   I suggest calling it ExternalCourseEnrollmentSummaryPartitionTask.  That way, if the data is not present, the ExternalCourseEnrollmentSummaryPartitionTask will fail instead of running enrollment with the wrong parameters.  

To do this, I would create ExternalCourseEnrollmentSummaryPartitionTask by inheriting from CourseEnrollmentSummaryPartitionTask, and overriding the requires() method.   Look at the definition of ExternalCourseEnrollmentPartitionTask in insights/enrollments.py for an example of how to do this.  Note that it also disables the overwrite_n_days parameter, which is good.

Once you have done this, you will find that you no longer need to create an interval and pass it around.  It should simplify the acceptance test a little in this respect.

2018-11-06 21:24 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +            '--interval', '2014-07-30-2016-09-08',
Once you use ExternalCourseEnrollmentSummaryPartitionTask, you should no longer need to pass --interval.

2018-11-07 06:28 UTC, asadiqbal08 commented
> One quick point: @brittneyexline noted that she thought "this repo can now be set up in docker and you can run the acceptance tests there." I just wanted to confirm that this is true. Look for the analytics section in the docker repo's readme.

@brianhw Yes I know but on local machine it takes a lot of time to execute than Jenkins machine.

2018-11-07 19:18 UTC, HassanJaveed84 commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +            url=url_path_join(self.warehouse_path, 'course_enrollment_summary', 'dt={}'.format(self.date)) + '/_SUCCESS'
I think this needs to point to the directory and not to the ```_SUCCESS``` file. 
```url=url_path_join(self.warehouse_path, 'course_enrollment_summary', 'dt={}'.format(self.date)) + '/'```
or one could possibly use this:
```url=self.hive_partition_path('course_enrollment_summary', self.date)```
See: https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/util/hive.py#L66

2018-11-07 19:23 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        )
Need to append a file name at the end of the remote file path. 

```
    self.upload_file(
        os.path.join(self.data_dir, 'input', 'course_enrollment_summary'),
        url_path_join(
            self.warehouse_path,
            'course_enrollment_summary',
            'dt={}'.format(self.DATE),
            'course_enrollment_summary_{}'.format(self.DATE),
        )
    )
```

2018-11-07 19:24 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +    def validate_marker(self, marker_path):
Don't think we need this.

2018-11-07 19:25 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        self.execute_sql_fixture_file('load_auth_userprofile.sql')
Why do we need this ?

2018-11-07 19:25 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        self.import_db.execute_sql_file(
Same for this ?

2018-11-07 19:28 UTC, HassanJaveed84 commented
I think you would also need to update ```expected_enterprise_enrollment_results``` method to include the newly added column, and then add it to the ```columns``` list in ```validate_enterprise_enrollment_table``` method.

2018-11-08 12:27 UTC, asadiqbal08 commented
@HassanJaveed84 I have incorporated your suggestions in the PR. Can you take another look around it ? [HERE](http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/1690/testReport/edx.analytics.tasks.tests.acceptance.test_enterprise_enrollments/EnterpriseEnrollmentAcceptanceTest/test_enterprise_enrollment_table_generation/) is the logs now.

2018-11-08 13:10 UTC, HassanJaveed84 commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +            url=self.hive_partition_path('course_enrollment_summary', self.date)
The path needs to have the date partition spec, like dt=date.

2018-11-08 15:19 UTC, asadiqbal08 commented
@brianhw @HassanJaveed84 I have updated the PR, Can you tell me is anything else missing to address in the PR? [HERE](http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/1691/testReport/edx.analytics.tasks.tests.acceptance.test_enterprise_enrollments/EnterpriseEnrollmentAcceptanceTest/test_enterprise_enrollment_table_generation/?auto_refresh=false) is the current logs.

2018-11-08 16:02 UTC, brianhw requested changes
Almost there!

2018-11-08 16:02 UTC, brianhw commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +            url=url_path_join(self.warehouse_path, 'course_enrollment_summary', 'dt={}'.format(self.date)) + '/'
I would prefer that this used:             
```
  url=url_path_join(self.warehouse_path, 'course_enrollment_summary', self.partition.path_spec) + '/'
```
And defined:
```
    @property
    def partition_value(self):
        """ Use a dynamic partition value based on the date parameter. """
        return self.date.isoformat()  # pylint: disable=no-member
```

2018-11-08 16:02 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        )
As written, this copies the TSV to the marker_path.   You could just use self.marker_path for the destination.  And you could use the _SUCCESS fixture file you created for the source.    If you're not using it here, then you could just not add it at all to the PR.  (I cannot put a comment on it, because it has no content, so I have to say it here.)

2018-11-08 16:02 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/fixtures/input/course_enrollment_summary
> +course-v1:edX+Open_DemoX+edx_demo_course2   13   honor    True    honor     2015-09-09 2016-09-08  2015-09-09  2015-09-09  2015-09-09
This is not required for the current functionality, but it might be good if the dates were changed so that they made more sense if someone else were to use this, especially since the fixture is not in the "enterprise" subdirectory.   The five dates at the end are first_enrollment_time, last_unenrollment_time, first_verified_enrollment_time, first_credit_enrollment_time and end_time.    The second user did not ever verify, so technically they should not have a first_verified_enrollment_time.   And end_time should be the end time of the interval when the summary was calculated, so it would be after 2016-09-08 at any rate.

2018-11-08 16:03 UTC, brianhw commented
Oh, and there are quality issues with the includes, according to the travis builds:
ERROR: /edx/app/analytics_pipeline/analytics_pipeline/edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py Imports are incorrectly sorted.
ERROR: /edx/app/analytics_pipeline/analytics_pipeline/edx/analytics/tasks/enterprise/enterprise_enrollments.py Imports are incorrectly sorted.

2018-11-08 19:53 UTC, asadiqbal08 commented on edx/analytics/tasks/tests/acceptance/fixtures/input/course_enrollment_summary
> +course-v1:edX+Open_DemoX+edx_demo_course2   13   honor    True    honor     2015-09-09 2016-09-08  2015-09-09  2015-09-09  2015-09-09
so do u meant, `first_verified_enrollment_time` should be empty and `end_time` should be after 2016-09-08 in this file ? right  ?

2018-11-08 19:56 UTC, brianhw commented
Yup.

On Thu, Nov 8, 2018 at 2:53 PM Asad Iqbal <notifications@github.com> wrote:

> *@asadiqbal08* commented on this pull request.
> ------------------------------
>
> In
> edx/analytics/tasks/tests/acceptance/fixtures/input/course_enrollment_summary
> <https://github.com/edx/edx-analytics-pipeline/pull/534#discussion_r232039295>
> :
>
> > @@ -0,0 +1,2 @@
> +course-v1:edX+Testing102x+1T2017   11   verified    True    verified     2015-09-09 2016-09-08  2015-09-09  2015-09-09  2015-09-09
> +course-v1:edX+Open_DemoX+edx_demo_course2   13   honor    True    honor     2015-09-09 2016-09-08  2015-09-09  2015-09-09  2015-09-09
>
> so do u meant, first_verified_enrollment_time should be empty and end_time
> should be after 2016-09-08 in this file ? right ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edx/edx-analytics-pipeline/pull/534#discussion_r232039295>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACaqz8vpluPr2QsycpGyC2nw6VUsb34Lks5utIvOgaJpZM4XjztV>
> .
>

2018-11-08 19:56 UTC, asadiqbal08 commented
> Oh, and there are quality issues with the includes, according to the travis builds:
> ERROR: /edx/app/analytics_pipeline/analytics_pipeline/edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py Imports are incorrectly sorted.
> ERROR: /edx/app/analytics_pipeline/analytics_pipeline/edx/analytics/tasks/enterprise/enterprise_enrollments.py Imports are incorrectly sorted.

Yeah I know, Thanks. I would fix this at the end. First problem is with the acceptance test failure over the jenkins machine :)

2018-11-08 20:09 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        self.marker_path = url_path_join(
I think this can be remove altogether ?

2018-11-08 20:10 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        )
And we can also probably remove this ? We only need to create the tsv file which is copied over down below.

2018-11-09 20:11 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +             'US', None, None, None, 'Percentage, 100 (#8)', 0.74, 100.00, 60.00, datetime.datetime(2016, 9, 8, 0, 0)]
Missing a comma here -- causes an error.

2018-11-12 17:24 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/fixtures/input/course_enrollment_summary
> +course-v1:edX+Testing102x+1T2017	2	verified	True	verified	2015-09-09	2016-09-08	2015-09-09	2015-09-09	2015-09-09
As you're joining ```course_enrollment_summary``` table with ```enterprise_enterprisecustomeruser``` based on ```user_id```. This file needs to have the same user_ids as in https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/tests/acceptance/fixtures/input/enterprise/lms/enterprise_enterprisecustomeruser.sql

2018-11-12 21:26 UTC, HassanJaveed84 commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +            url=url_path_join(self.warehouse_path, 'course_enrollment_summary', 'dt={}'.format(self.date)) + '/'
@asadiqbal08 I think this is the culprit of your failing test. You have to define ```partition_value``` 
the default implementation is 
```
    @property
    def partition_value(self):  # pragma: no cover
        """ Use a dynamic partition value based on the date parameter. """
        return self.interval.date_b.isoformat()  # pylint: disable=no-member
```
Where self.interval.date_b defaults to Today's date. You need to override it like Brian suggested so it uses the correct date(passed from the acceptance test) and not Today's date. 
The hive table ```course_enrollment_summary``` which gets loaded is actually empty if you don't override this.

2018-11-13 14:17 UTC, HassanJaveed84 commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +            JOIN course_enrollment_summary course_enrollment_summary
I'm wondering if this should be a ```LEFT JOIN``` ?

2018-11-15 09:31 UTC, asadiqbal08 commented
@brianhw @HassanJaveed84 Acceptance tests have been passed, You can see the build details [HERE](http://jenkins-ci.analytics.edx.org/view/All/job/edx-analytics-pipeline-acceptance-test-manual/1709/)
Kindly take a look around the changes, If we are good then let me know. Thanks.

2018-11-15 15:45 UTC, brianhw reviewed
Note that once this merges, the scheduling of the enterprise jobs will need to be made much later, to run after the regular enrollment calculations have been run for the previous day.   This can take hours.  So a question I have is whether there is a quicker way to get roughly the same information:   can someone check to see if the values that this would find for unenrollment timestamps would match the last-modified time for an entry in student_courseenrollment?    The premise is that if a student were currently unenrolled, the last modified date would be the unenrollment time if we assume that they wouldn't do anything else to modify that table once they unenrolled.    @brittneyexline  @mattdrayer ?

2018-11-15 15:45 UTC, brianhw commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +                ) enrollment_summary
Why is there a sub-select here?   Unlike user_activity_by_user, I presume that you don't have to find a MAX, but just find a single row.   So why not just join with course_enrollment_summary?

2018-11-15 15:45 UTC, brianhw commented on edx/analytics/tasks/enterprise/tests/test_enterprise_enrollments.py
> +            'unenrollment_timestamp'
nit:  add a comma, so that the next addition doesn't need to change it.

2018-11-15 15:45 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +        print("TEST:" + str(results))
This can be removed.

2018-11-28 11:50 UTC, asadiqbal08 commented
@brianhw @brittneyexline Are we good with these change set ? Waiting for the response. Thanks

2018-11-28 14:07 UTC, zubair-arbi commented
@brianhw @asadiqbal08 what about the coverage failure? Are we missing something in tests?

2018-11-28 14:09 UTC, zubair-arbi approved these changes
Overall changes looks good to me 👍

2018-11-28 21:43 UTC, brianhw commented
I raised a question two weeks ago on which I did not get an answer, about the external dependency on enrollment calculations having been run.    Note that once this merges, the scheduling of the enterprise jobs will need to be altered.   As they currently are, they would be running before enrollment completes, and it will fail because the expected enrollment data is not present.    There are several choices:
# Schedule it to run much later, to run after the regular enrollment calculations have been run for the previous day. This can take hours. 
# Modify the code to use the most recent enrollment calculations available, which most likely be yesterday's.  Or hardcode it to always use yesterday's.
# Consider discovery into a more heuristic way to get unenrollments.   (I mentioned the possibility that the values that this would find for unenrollment timestamps would match the last-modified time for an entry in student_courseenrollment.  If they did, that would be data that would be quicker to include.)

2018-12-04 18:45 UTC, brittneyexline commented
@asadiqbal08 i think you need to choose one of @brianhw's recommendations before this can merge. the first option seems problematic from a performance standpoint, but i think options 2 and 3 seem viable, but with different tradeoffs. i would think about those tradeoffs and how difficult it would be to make either change, and make a choice from there.
fyi @georgebabey

2018-12-05 12:22 UTC, asadiqbal08 commented
@brianhw As @brittneyexline highlighted the performance concern regarding the first option, I think, we should no go with that. 
From point 2 and 3, I will choose to go with option 2 as it seems me simple to handle. For option 3, We need to do more changes and may be we need to modify the tests as well at that stage. 

As you suggested the option 2 that we use the most recent enrollment calculations available, which most likely be yesterday's then I think we can avail via modifying the [partition_value](https://github.com/edx/edx-analytics-pipeline/pull/534/files#diff-7ef89a9bf47ca9cc8336e883532141c7R124) property to go one day back . 

    @property  
    def partition_value(self):  # pragma: no cover
        """ Use a dynamic partition value based on the date parameter. """
        return (self.date - timedelta(days=1)).isoformat()  # pylint: disable=no-member

Please let me know is that approach would be helpful to handle the issue ? 

@shamck @georgebabey  FYI

2018-12-05 14:45 UTC, brianhw requested changes

2018-12-05 14:45 UTC, brianhw commented on edx/analytics/tasks/enterprise/enterprise_enrollments.py
> +        return (self.date - datetime.timedelta(days=1)).isoformat()  # pylint: disable=no-member
I know I said that "or you can run with yesterday's enrollment data" (or words to that effect), but I really suggest instead that we find the latest date for which we have enrollment data.   To that end I point you to https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/warehouse/load_warehouse_bigquery.py#L203-L210 as an example of how to find the latest date.   Put that into an __init__ method (with 'course_enrollment_summary' in place of 'internal_reporting_user_activity') to find the self.load_date, and then return that value here instead of the calculation you have.

2018-12-06 11:48 UTC, asadiqbal08 commented
@brianhw ready for final review.

2018-12-06 20:16 UTC, brianhw approved these changes
LGTM!   Just one nit.  👍

2018-12-06 20:16 UTC, brianhw commented on edx/analytics/tasks/tests/acceptance/test_enterprise_enrollments.py
> +from edx.analytics.tasks.tests.acceptance import AcceptanceTestCase, get_target_for_local_server
nit: I don't happen to see where get_target_for_local_server is being used.  Unneeded?

2018-12-10 08:17 UTC, asadiqbal08 commented
Guys so are we go ahead with merge. @brianhw @HassanJaveed84 ?

2018-12-10 11:58 UTC, saleem-latif approved these changes
Looks Good 👍

2018-12-10 11:59 UTC, merged