SE-1032 Adds option to store anonymous user events in module_engagement hive table
openedx-unsupported/edx-analytics-pipeline pull request #734
Opened 2019-06-14 08:48 UTC by pomegranited

Since the Public Courseware feature was released, our client's engagement data has dropped significantly, and so they would like a way to count the anonymous hits to this content.  They use the per-learner module_engagement hive tables for their own internal reporting, and so only need the data recorded there.

Add this configuration to store anonymous user records under the given replacement username, e.g.
```cfg
[module-engagement]
store_anonymous_username = ANONYMOUS USER
```

**JIRA tickets**:  OSPR

**Merge deadline**: None, though we would appreciate feedback on the approach ASAP so we can decide whether to merge to our client's branch now.

**Testing instructions**:

1. Set up the [Analytics Pipeline docker devstack](https://github.com/edx/devstack#getting-started-on-analytics)
1. Open the pipeline shell:
   ```bash
   make analytics-pipeline-shell
   ```
1. Copy the anonymous user tracking logs into the hdfs /data dir:
   * [anon_tracking.log](https://github.com/edx/edx-analytics-pipeline/files/3289758/anon_tracking.log)
   * [honor_tracking.log](https://github.com/edx/edx-analytics-pipeline/files/3289759/honor_tracking.log)
   ```
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ hdfs dfs -put anon_tracking.log /data/
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ hdfs dfs -put honor_tracking.log /data/
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ hdfs dfs -ls /data
Found 2 items
-rw-r--r--   3 hadoop hadoop      12897 2019-06-11 06:32 /data/anon_tracking.log
-rw-r--r--   3 hadoop hadoop      12972 2019-06-11 06:42 /data/honor_tracking.log
    ```
1. Check the hive database  -- a clean install won't have any tables in it, but even if you do, there shouldn't be any anonymous user records in the `module_engagement` table yet.
   ```bash
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ hive
   hive> show tables;
   hive> select * from module_engagement;
   ```
1. Check out this branch and install it: 
   ```bash
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ make install
   ```
1. Add custom configuration for the module-engagement tasks, which ignores anonymous user records by default:
   ```bash
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ echo "[module-engagement]
   allow_empty_insert = true" >  override.cfg
   ```
1. Process the tracking data loaded into hdfs above.
   ```bash
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ START_DATE=2019-06-10
; TODAY=`date +%Y-%m-%d`
   # Load enrollments for the interval
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ launch-task ImportEnrollmentsIntoMysql --interval $START_DATE-$TODAY --local-scheduler
   # Process per-learner data for the interval
   launch-task ModuleEngagementIntervalTask --interval $START_DATE-$TODAY --local-scheduler
   ``` 
1. Check that only the honor user records are in hive
   ```bash
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ hive
   hive> select * from module_engagement;
   edX/DemoX/Demo_Course_2 honor   2019-06-10      video   i4x-edX-DemoX-video-8c0028eb2a724f48a074bc184cd8635f    viewed 2       2019-06-10
   edX/DemoX/Demo_Course   honor   2019-06-10      video   i4x-edX-DemoX-video-8c0028eb2a724f48a074bc184cd8635f    viewed 2       2019-06-10
   Time taken: 1.929 seconds, Fetched: 4 row(s)
  ``` 
1. Update config to store anonymous users under the username, `ANONYMOUS USER`
   ```bash
   echo "[module-engagement]
   store_anonymous_username = ANONYMOUS USER
   allow_empty_insert = true" >  override.cfg
   ```
1. Overwrite the module engagement data to include these anonymous user records
   ```bash
   launch-task ModuleEngagementIntervalTask --interval $START_DATE-$TODAY --local-scheduler --overwrite-from-date $START_DATE  --overwrite-mysql
   ```
1. Check that there are now both honor and anonymous user records present in the table.
   ```bash
   hadoop@analyticspipeline:/edx/app/analytics_pipeline/analytics_pipeline$ hive
   hive> select * from module_engagement;
   edX/DemoX/Demo_Course_2 ANONYMOUS USER  2019-06-10  video   i4x-edX-DemoX-video-8c0028eb2a724f48a074bc184cd8635f viewed  2   2019-06-10
   edX/DemoX/Demo_Course_2 honor   2019-06-10  video   i4x-edX-DemoX-video-8c0028eb2a724f48a074bc184cd8635f    viewed  2 2019-06-10
   edX/DemoX/Demo_Course   ANONYMOUS USER  2019-06-10  video   i4x-edX-DemoX-video-8c0028eb2a724f48a074bc184cd8635f viewed  2   2019-06-10
   edX/DemoX/Demo_Course   honor   2019-06-10  video   i4x-edX-DemoX-video-8c0028eb2a724f48a074bc184cd8635f    viewed  2 2019-06-10
   Time taken: 1.929 seconds, Fetched: 4 row(s)
   ```

**Author notes and concerns**:

1. Acceptance tests are in the works.
1. This change does not modify the various summary tables generated by module_engagement, so the data will only be visible in the hive table itself.
   The summary tables also require that the per-learner data be linked to an enrollment record, which anonymous records cannot be.  So future enhancements would be required to make to make this information visible as appropriate in Insights.
1. Any logs with anonymous user events will need to be re-processed with this option enabled in order to fix the historical data records.

**Reviewers**
- [ ] @gr4yscale
- [ ] edX reviewer[s] TBD

Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

2019-06-14 08:48 UTC, edx-webhook commented
Thanks for the pull request, @pomegranited! I've created [OSPR-3659](https://openedx.atlassian.net/browse/OSPR-3659) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2019-06-14 14:54 UTC, brianhw requested changes
This looks good, Jill!  And thanks for checking in with us.   Just the one small change.

2019-06-14 14:54 UTC, brianhw commented on edx/analytics/tasks/insights/module_engagement.py
> +        if not username:
Can this test be moved back before the length test above?  Otherwise the len(None) test on line 130 will fail.

2019-06-17 08:53 UTC, pomegranited commented on edx/analytics/tasks/insights/module_engagement.py
> +        if not username:
Sure thing @brianhw -- done with 5d7bb2a .

2019-06-17 19:21 UTC, brianhw approved these changes
LGTM.  👍 

Do you want to merge it, or do you need me to do so?   (I can't remember.)

2019-06-18 01:07 UTC, pomegranited commented
Thanks @brianhw :)  I don't have permission to merge, so will need your help there too.

I'm really struggling with getting the acceptance tests working for some reason -- whenever I add any new anonymous tracking records to the fixture data for [ModuleEngagementAcceptanceTest](https://github.com/edx/edx-analytics-pipeline/blob/5d7bb2afa0955834d4daadefcbfd2417e98b5a1b/edx/analytics/tasks/tests/acceptance/test_module_engagement.py#L14), it mucks up the [data returned by ES](https://github.com/edx/edx-analytics-pipeline/blob/5d7bb2afa0955834d4daadefcbfd2417e98b5a1b/edx/analytics/tasks/tests/acceptance/test_module_engagement.py#L174), even when the default "skip anonymous records" is enabled.  So still working that out.

Also, @gr4yscale is not getting the same results as I do when I run the manual testing steps.  Did you run them ok ?

2019-06-21 02:21 UTC, pomegranited commented
@brianhw I worked out the acceptance test issues at last -- had to I learn a bit more about how adding another "user" to the processed course logs changes the metrics for the whole course.  So instead of messing with the existing courses, I added a new one for the anonymous user.

Once @gr4yscale verifies my tests, we should be good to merge.  Thanks for your help!

2019-06-26 05:07 UTC, brianhw commented
Great!   I'll wait for a second thumb after verification, and then I'll verify and merge.

2019-07-09 12:56 UTC, gr4yscale commented
@pomegranited 
        :+1:

        - [ ] I tested this
        - [x] I read through the code
        - [ ] I checked for accessibility issues n/a
        - [x] Includes documentation
        - [x] I made sure any change in configuration variables is reflected in the corresponding
            client's `configuration-secure` repository.

2019-07-10 00:07 UTC, pomegranited commented
Thank you for checking the code and running the acceptance tests, @gr4yscale !  The manual testing steps work for me, but @brianhw  might want to check them himself before merging.

Ready for you now, @brianhw :)

2019-07-13 06:40 UTC, brianhw commented
I'll try to test it this weekend.

2019-07-18 13:49 UTC, brianhw commented
Jill, your testing instructions are as detailed as ever!   

I did encounter some issues, however, and that perhaps is what was the difference with manual testing before.  In particular, I found I needed to run "launch-task ModuleEngagementWorkflowTask --date $TODAY --overwrite-n-days 39 --local-scheduler" instead of "launch-task ModuleEngagementWorkflowTask --interval $START_DATE-$TODAY --local-scheduler", as that task doesn't support --interval.  

Once I ran it, I then found that despite the value of --overwrite-n-days that I used, that it only went back 14 days, so it never included the day on which the activity was observed.  So I changed the run to something smaller:   "launch-task ModuleEngagementWorkflowTask --date 2019-06-12 --overwrite-n-days 4 --local-scheduler".  But that in turn required rerunning the enrollment:  "launch-task ImportEnrollmentsIntoMysql --interval $START_DATE-2019-06-12 --local-scheduler".   But before I did that, I discovered that there were no enrollment entries in Hive either from the original run.   It seems that while CourseEnrollmentTask ran with --interval $START_DATE-2019-07-19 originally, the argument that got passed to CourseEnrollmentEventsTask was only a three-day interval:  --interval 2019-07-17-2019-07-19.   Fortunately, running with 2019-06-12 as the end date worked, because then CourseEnrollmentEventsTask was called with --interval 2019-06-10-2019-06-12, which worked to get the relevant enrollment events. 

I'll update here once I get the PR testing complete.  My analytics devstack is pretty slow!

2019-07-18 17:57 UTC, merged

2019-07-18 17:59 UTC, brianhw commented
Manual tests eventually ran, basically by using 2019-06-12 instead of $TODAY.     All set now!

2019-07-18 23:30 UTC, pomegranited commented
@brianhw  Ach I'm so sorry I had so many errors in my test instructions!  I should have re-run everything from scratch before I posted them, and taken into account that `$TODAY` was going to move on significantly from the dates in the data.  I've updated them as best I could using your corrections for future reference  -- that's why I go into so much detail, so I have notes down for next time!

Thank you for testing and merging! 😄

2019-07-18 23:51 UTC, pomegranited commented
@brianhw  CC @nedbat  Is it possible to get this cherry-picked into `ironwood.master`, since it supports the [Public Courses](https://open.edx.org/blog/public-course-content-in-ironwood/) feature added for Ironwood?

2019-07-22 20:33 UTC, nedbat commented
@pomegranited I'm fine with adding this to Ironwood, but it doesn't cherry-pick cleanly.  Would you mind making a pull request against open-release/ironwood.master with the change?  The merge commit is 65f935084ec65117857d484a1a1bd869f3bb093b.  Thanks.

2019-07-23 02:02 UTC, pomegranited commented
Thank you @nedbat !  Done.