Dynamic Program Course Count
openedx-unsupported/edx-analytics-pipeline pull request #785
Opened 2019-12-19 16:19 UTC by Zacharis278

@edx/masters-devs 

Aggregate program report columns will now be based on the number of courses in the program.

---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

2019-12-20 16:08 UTC, michaelroytman requested changes

2019-12-20 16:08 UTC, michaelroytman commented on edx/analytics/tasks/programs/program_reports.py
> +        authoring_org, program_uuid, user_id, course_key, timestamp = key  # pylint: disable=unused-variable
Does replacing `course_key` with `_` to ignore that variable avoid flagging that particular PyLint rule?

2019-12-20 16:08 UTC, michaelroytman commented on edx/analytics/tasks/programs/program_reports.py
> +            ('audit_enrollment_counts', cnt_learners_in_audit.values()),
I don't believe that the `dict` type affords us any guarantee about the order of the values returned by `values`. I think that, in this case, it probably happens to work out that the order of the values corresponds to the numeric order of the corresponding keys, but I don't think we can confidently rely on that. I'm basing this on [these](https://docs.python.org/3.5/library/stdtypes.html#dictionary-view-objects) docs, 

> Keys and values are iterated over in an arbitrary order which is non-random, varies across Python implementations, and depends on the dictionary’s history of insertions and deletions

We can't make any assessments about how we're inserting into the dictionary either, because each call to `aggregate_enrollment_totals` will be called with an unpredictable number for the `number_of_enrollments` parameter, so I think the the order of items returned by `values` is unpredictable.

I just worry that there will be some case in which the order of insertions or modifications to the dict will result in an ordering that we don't expect, and that will be a hard bug to track down.

I wonder if something like this might ensure a consistent ordering to the values:

```
def _get_enrollment_count_values(cnt_enrollments):
    values = []
    for key in sorted(cnt_enrollments.keys())
         values.append(cnt_enrollments[key])
    return values
```

What do you think?

2019-12-20 16:08 UTC, michaelroytman commented on edx/analytics/tasks/programs/program_reports.py
> +        yield self.clone(CountProgramCohortEnrollments)
I don't understand why we need to yield these two dependencies. Does it not work to just return them as

` return self.clone(ExportVerticaTableToS3Task, table_name=self.programs_table, overwrite=(self.overwrite_export and self.overwrite)), self.clone(CountProgramCohortEnrollments)`?

That's how I saw multiple dependencies being returned [here](https://luigi.readthedocs.io/en/stable/tasks.html#task-requires). Is there something about the use of `yield` that's significant?

2019-12-20 16:08 UTC, michaelroytman commented on edx/analytics/tasks/programs/program_reports.py
> +        result = OrderedDict([
This is so much nicer to read now! :)

2019-12-20 16:08 UTC, michaelroytman commented on edx/analytics/tasks/programs/program_reports.py
> +        if export_delimiter in line:
Could you add a comment explaining why this is necessary? Maybe something along the lines of `mapper` will receive lines from both tables, and the `if` block covers the `program_metadata` table export, and the `else` block handles the output of the `CountProgramCohortEnrollments` task?

2019-12-20 17:58 UTC, Zacharis278 commented on edx/analytics/tasks/programs/program_reports.py
> +            ('audit_enrollment_counts', cnt_learners_in_audit.values()),
ah yes good catch

2019-12-20 18:08 UTC, Zacharis278 commented on edx/analytics/tasks/programs/program_reports.py
> +        yield self.clone(CountProgramCohortEnrollments)
end result is the same for both, I just thought yield made it cleaner to read. Seems like both approaches are used throughout the repo

2020-01-03 15:43 UTC, Zacharis278 commented
I also added a new task to act as the main entry point to run both reports

https://github.com/edx/edx-analytics-pipeline/pull/785/files#diff-3613ee53c6cd2dbc3281be68b95033ccR676

2020-01-06 17:27 UTC, pwnage101 commented on edx/analytics/tasks/programs/program_reports.py
> +            table_name=self.enrollments_table,
How is it possible to use `table_name` here, given that it was formerly provided by ProgramsReportTaskMixin but removed in this PR?

2020-01-06 17:27 UTC, pwnage101 commented on edx/analytics/tasks/programs/program_reports.py
> +        a specific number of courses
Can you clarify here that `counts` is a mapping of number (or more) of enrollments (key) to number of users (value), if that's correct?  Based on the wording of the docstring and the source code, it still took me a long time to actually understand which was the key and which was the value.

2020-01-06 17:58 UTC, Zacharis278 commented on edx/analytics/tasks/programs/program_reports.py
> +            table_name=self.enrollments_table,
I had to remove it from the mixin since `table_name` isn't the same every time we require the `ExportVerticaTableToS3Task`.  This is just mapping the appropriate value into `table_name` for that export task.

2020-01-06 18:17 UTC, Zacharis278 commented on edx/analytics/tasks/programs/program_reports.py
> +        a specific number of courses
I changed the wording on this to (hopefully) make it more clear.

2020-01-06 18:35 UTC, pwnage101 commented on edx/analytics/tasks/programs/program_reports.py
> +            table_name=self.enrollments_table,
Oh, whoops, i confused the parameters of this task and ExportVerticaTableToS3Task.

2020-01-07 20:01 UTC, Zacharis278 commented
@pwnage101 / @MichaelRoytman any further comments on this?  Can I get a thumb to merge?

2020-01-07 22:17 UTC, pwnage101 approved these changes
I reviewed based on how good this looks as a luigi pipeline, map/reduce logic, python style, but I'm less familiar with the actual business logic.

2020-01-08 14:37 UTC, Zacharis278 commented
👍 Makes sense thanks!  PR template mentioned needing an approval so figured I should wait for that.

2020-01-08 14:38 UTC, merged