ENT-2664 added task for inserting course_structure to mysql
openedx-unsupported/edx-analytics-pipeline pull request #807
Opened 2020-03-10 11:15 UTC by irfanuddinahmad

Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

2020-03-17 11:22 UTC, HassanJaveed84 commented on edx/analytics/tasks/warehouse/load_internal_reporting_course_structure.py
> +    overwrite_hive = luigi.BoolParameter(
is this being used ?

2020-03-17 11:31 UTC, HassanJaveed84 commented on edx/analytics/tasks/tests/acceptance/test_internal_reporting_course_structure.py
> +            self.assertEqual(len(results), CountRecords)
Can we leverage `validate_course_structure` method to do the validation ? It might require a little refactoring, passing in a cursor(vertica or mysql).

2020-03-17 15:16 UTC, irfanuddinahmad commented on edx/analytics/tasks/warehouse/load_internal_reporting_course_structure.py
> +    overwrite_hive = luigi.BoolParameter(
Removed

2020-03-20 17:55 UTC, ziafazal requested changes
@irfanuddinahmad completed first round of review.

2020-03-20 17:55 UTC, ziafazal commented on edx/analytics/tasks/warehouse/load_internal_reporting_course_structure.py
> +class LoadInternalReportingCourseStructureToMysqlTask(WarehouseMixin, MysqlInsertTask):
I think we don't need this

2020-03-20 17:55 UTC, ziafazal commented on setup.cfg
> +    enterprise_engagements = edx.analytics.tasks.enterprise.enterprise_engagement_report:ImportEnterpriseEngagementsIntoMysql
typo in the class name

2020-03-20 17:55 UTC, ziafazal commented on edx/analytics/tasks/enterprise/enterprise_engagement_report.py
> +class ImportEnterpriseEngagementIntoMysql(luigi.WrapperTask):
should be decorated with `workflow_entry_point`

2020-03-20 17:55 UTC, ziafazal commented on edx/analytics/tasks/enterprise/enterprise_engagement_report.py
> +            AggregateInternalReportingUserTableHive(
why we need this Task?

2020-03-20 17:55 UTC, ziafazal commented on edx/analytics/tasks/enterprise/enterprise_engagement_report.py
> +            ModuleEngagementWorkflowTask(
instead of workflow task we can call underlying partition task `ModuleEngagementSummaryPartitionTask`

2020-03-20 17:55 UTC, ziafazal commented on edx/analytics/tasks/enterprise/enterprise_engagement_report.py
> +    enterprise_name = StringField(length=255, nullable=False, description='')
add `enterprise_user_id` too which can be joined later with enterprise user table.

2020-03-20 17:55 UTC, ziafazal commented on edx/analytics/tasks/enterprise/enterprise_engagement_report.py
> +        return 'enterprise_engagement_report'
table name should be same as mysql table `enterprise_learner_engagement `

2020-03-20 18:11 UTC, irfanuddinahmad commented on edx/analytics/tasks/enterprise/enterprise_engagement_report.py
> +            AggregateInternalReportingUserTableHive(
Hive mapping for production.d_user

2020-03-20 18:11 UTC, irfanuddinahmad commented on edx/analytics/tasks/enterprise/enterprise_engagement_report.py
> +            ModuleEngagementWorkflowTask(
The underlying table for the summary task is different from module_engagement

2020-03-20 18:13 UTC, irfanuddinahmad commented on edx/analytics/tasks/warehouse/load_internal_reporting_course_structure.py
> +class LoadInternalReportingCourseStructureToMysqlTask(WarehouseMixin, MysqlInsertTask):
Yes. This was the initial solution approach.

2024-01-09 16:30 UTC, closed without merging