ENT-3005: Added null for order discount price when order lines greater than one
openedx-unsupported/edx-analytics-pipeline pull request #820
Opened 2020-06-29 16:43 UTC by irfanuddinahmad

Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

2020-06-29 18:06 UTC, moconnell1453 approved these changes

2020-06-30 05:38 UTC, HammadAhmadWaqas requested changes
Can we update our test to support our changes? otherwise looks good.

2020-07-01 06:19 UTC, muhammad-ammar approved these changes
LGTM

2020-07-02 06:37 UTC, HammadAhmadWaqas approved these changes

2020-07-06 05:47 UTC, saleem-latif approved these changes

2020-07-07 14:07 UTC, doctoryes approved these changes
I don't know if the business logic is correct. But the SQL and tests LGTM. 👍

2020-07-08 12:29 UTC, merged