remove OEP-10 so this repo is no longer shipped with openedx releases.
openedx-unsupported/edx-analytics-pipeline pull request #841
Opened 2020-11-03 19:20 UTC by macdiesel

Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

2020-11-03 19:27 UTC, natabene commented
@macdiesel I am for it, but cannot really review from engineering perspective. @nedbat , any comments?

2020-11-03 22:08 UTC, nedbat approved these changes

2023-12-13 17:27 UTC, kdmccormick commented
Relevant DEPR: https://github.com/openedx/public-engineering/issues/36

2023-12-13 17:27 UTC, kdmccormick approved these changes

2023-12-13 17:27 UTC, feanil approved these changes

2023-12-13 17:30 UTC, kdmccormick requested changes
Wait, I'm not sure Insights deprecated. Just the learner view and supporting code is.

Is there another DEPR ticket I'm missing?

2023-12-13 20:33 UTC, closed without merging